modelix/modelix.core

.github/workflows/publish.yml, docker-build-model.sh, docker-ci.sh, modelix-version.sh
The model server docker image is now built and published as a multi-architecture image for linux/amd64 and linux/arm64.
See related https://github.com/modelix/modelix/pull/238
=> Multi-Arch build for model server

gradle.properties, kotlin-js-store/yarn.lock, model-api-gen-gradle-test/build.gradle.kts, model-api/build.gradle.kts, ts-model-api/build.gradle.kts, ts-model-api/package-lock.json, ts-model-api/package.json
The multiplatform plugin finally supports Gradle composite builds.
=> MODELIX-417 Migration to Kotlin 1.8.20

authorization/build.gradle.kts, build.gradle.kts, gradle/libs.versions.toml, gradle/wrapper/gradle-wrapper.properties, light-model-client/build.gradle.kts, metamodel-export/build.gradle.kts, model-api-gen-runtime/build.gradle.kts, model-api-gen/build.gradle.kts, model-api/build.gradle.kts, model-client/build.gradle.kts, model-server-api/build.gradle.kts, model-server-lib/build.gradle.kts, model-server/build.gradle.kts, settings.gradle.kts
=> build: use version catalog instead of properties

model-server-lib/src/main/kotlin/org/modelix/model/server/light/LightModelServer.kt
https://issues.modelix.org/issue/MODELIX-411
=> MODELIX-411 /health endpoint

metamodel-export/org.modelix.metamodel.export/models/org.modelix.metamodel.export.mps, model-api-gen-gradle-test/build.gradle.kts, model-api-gen-gradle-test/src/test/kotlin/GeneratedApiTest.kt, model-api-gen-runtime/src/commonMain/kotlin/org/modelix/metamodel/IPropertyValueSerializer.kt, model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/GeneratorInput.kt, model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/MetaModelGenerator.kt, model-api/src/commonMain/kotlin/org/modelix/model/data/MetaModelData.kt
https://issues.modelix.org/issue/MODELIX-458
=> MODELIX-458 Using generated enums leads to IllegalArgumentException

model-api-gen-gradle/src/main/kotlin/org/modelix/metamodel/gradle/MetaModelGradlePlugin.kt, model-api/src/commonMain/kotlin/org/modelix/model/data/MetaModelData.kt
https://issues.modelix.org/issue/MODELIX-456
=> MODELIX-456 exportMetaModelFromMps caches too eagerly

model-api-gen-gradle-test/build.gradle.kts, model-api-gen-gradle-test/package.json, model-api-gen-gradle-test/tsconfig.json, model-api-gen-gradle-test/tslint.json, model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/ConceptInLanguage.kt, model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/GeneratorInput.kt, model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/MetaModelGenerator.kt, model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/TypescriptMMGenerator.kt, model-api/src/jsMain/kotlin/org/modelix/model/api/NodeAdapterJS.kt, ts-model-api/src/TypedNode.ts
=> fix(model-api-gen): added tests for the typescript generator

model-client/src/commonMain/kotlin/org/modelix/model/operations/MoveNodeOp.kt, model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/ModelImporter.kt, model-sync-lib/src/commonTest/kotlin/org/modelix/model/sync/ModelImporterTest.kt
I re-implemented the algorithm in the ModelImporter that should be more efficient in time and in memory.
=> proposal for a more efficient model sync algorithm

build.gradle.kts
https://issues.modelix.org/issue/MODELIX-470
=> MODELIX-470 API ref pipeline is broken

mps-model-server-plugin/build.gradle.kts, mps-model-server-plugin/src/main/kotlin/org/modelix/model/server/mps/MPSModelServer.kt
Was already implemented in
https://github.com/modelix/modelix/pull/273.
Just copied it to here and converted it to Kotlin.
=> feat(mps-model-server-plugin): 'indexer' health check

modelql-client/src/jvmTest/kotlin/org/modelix/modelql/client/HtmlBuilderTest.kt, modelql-core/src/commonMain/kotlin/org/modelix/modelql/core/IsEmptyStep.kt, modelql-core/src/commonTest/kotlin/org/modelix/modelql/core/ModelQLTest.kt
isEmpty always returned false.
Fixes: MODELIX-528
=> fix(modelql): let isEmpty return true on empty inputs

docs/global/modules/core/pages/reference/component-mps-model-server-plugin.adoc, docs/global/modules/core/partials/nav-reference.adoc
=> docs(mps-model-server-plugin): document available health checks

model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/TypescriptMMGenerator.kt
The generator uses string templates to generate the TypeScript code. It's hard to get the indentation right with them.
There is now a post-processing step that searches for curly brackets to determine the correct indentation level.
Also, all the empty lines are removed, because it was inconsistent where they were inserted.
=> fix(model-api-gen): indentation in generated TypeScript files

bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/ModelSyncGradlePlugin.kt, bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/config/ModelSyncGradleSettings.kt, bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/tasks/GenerateAntScriptForMps.kt, bulk-model-sync-lib/build.gradle.kts, bulk-model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/bulk/ModelImporter.kt, bulk-model-sync-solution/solutions/org.modelix.mps.model.sync.bulk/models/org.modelix.mps.model.sync.bulk.mps, docs/global/modules/core/pages/reference/component-bulk-model-sync-gradle.adoc
This PR adresses 2 pain points:
- Including multiple modules required listing them individually. As a shortcut they can now be included by specifying a prefix.
- The sync was almost like a black box. This PR adds some progress indicators.
=> MODELIX-560 bulk-model-sync quality of life improvements

.github/workflows/docs.yaml, build.gradle.kts, docs/global/modules/core/partials/nav-howto.adoc
Also enable the generation of a `/latest` path for API
=> MODELIX-591: Add modeQL doc tree and generate latest API symlink

docs/global/antora.yml
This PR relates to and is explained in https://github.com/modelix/modelix.docs/pull/18
=> docs: remove the version from the component

light-model-client/build.gradle.kts, light-model-client/src/commonMain/kotlin/org/modelix/client/light/LightModelClient.kt, light-model-client/src/jvmTest/kotlin/org/modelix/client/light/LightModelClientTest.kt, model-api-gen-runtime/src/commonMain/kotlin/org/modelix/metamodel/ITypedNode.kt, model-client/build.gradle.kts, model-client/src/commonMain/kotlin/org/modelix/model/IncrementalBranch.kt, model-client/src/commonTest/kotlin/org/modelix/model/IncrementalBranchTest.kt, model-server-lib/src/main/kotlin/org/modelix/model/server/light/LightModelServer.kt
Dynamic dependency tracking is a technique often used by UI frameworks for updating the UI automatically. [modelix.incremental](https://github.com/modelix/modelix.incremental/) provides some generic infrastructure for that. With the changes in this PR the [modelix.text-editor](https://github.com/modelix/modelix.text-editor) can work on models managed by the (light-)model-client.
The vue.js integration can also be simplified by just registering a listener in [DependencyTracking](https://github.com/modelix/modelix.incremental/blob/master/src/commonMain/kotlin/org/modelix/incremental/DependencyTracking.kt) and forwarding the read/write events to vue.js.
=> Integration of (light-)model-client with modelix.incremental

vue-model-api/build.gradle.kts
Caching resulted in publishing the vue-model-api with under the wrong version. This made the publishing workflow fail.
This was the reason for the last two failing publish workflows:
- https://github.com/modelix/modelix.core/actions/runs/6863094083
- https://github.com/modelix/modelix.core/actions/runs/6875497304
=> build(vue-model-api): remove faulty caching for package.json

build.gradle.kts, bulk-model-sync-gradle-test/build.gradle.kts, bulk-model-sync-gradle-test/ci.sh, bulk-model-sync-gradle-test/settings.gradle.kts, bulk-model-sync-gradle/build.gradle.kts, bulk-model-sync-lib/build.gradle.kts, gradle/libs.versions.toml, kotlin-utils/build.gradle.kts, model-api-gen-gradle-test/build.gradle.kts, model-api-gen-gradle-test/settings.gradle.kts, model-api-gen-gradle/build.gradle.kts, model-api/build.gradle.kts, model-client/build.gradle.kts, model-datastructure/build.gradle.kts, model-server/build.gradle.kts, mps-model-server-plugin/build.gradle.kts, settings.gradle.kts, ts-model-api/build.gradle.kts
[MODELIX-533](https://issues.modelix.org/issue/MODELIX-533)
=> MODELIX-533 Use repository content filtering

model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
So far, when putting multiple values via objects/put, a database transaction was created and committed for every value. That is unbelievably slow with a real database. This commit changes the implementation of the endpoint to use `putAll` instead of multiple `put` calls, effectively reducing the whole operation to a single transaction.
This is a `fix` commit and not a `perf` one as the previous implementation completely broke some known use cases due to ending in timeouts.
=> fix(model-server): use one large transaction when putting many values

model-server/Dockerfile, model-server/build.gradle.kts, model-server/src/main/kotlin/org/modelix/model/server/Main.kt, model-server/src/main/kotlin/org/modelix/model/server/templates/PageWithMenuBar.kt
Fixes regression introduced by #353
=> MODELIX-685 Resource based routing breaks docker container of model-server 

api/model-server-html.yaml, gradle/libs.versions.toml, model-server/build.gradle.kts, model-server/src/test/kotlin/org/modelix/model/server/handlers/ContentExplorerTest.kt
The route to post the expanded nodes was not found after #353.
=> MODELIX-701 Content explorer shows no content

api/model-server.yaml, gradle/libs.versions.toml, model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt, model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/CLVersion.kt, model-datastructure/src/commonMain/kotlin/org/modelix/model/persistent/HashUtil.kt, model-server-api/build.gradle.kts, model-server-api/src/commonMain/kotlin/org/modelix/model/server/api/v2/VersionDelta.kt, model-server/src/main/kotlin/org/modelix/model/server/CmdLineArgs.kt, model-server/src/main/kotlin/org/modelix/model/server/Main.kt, model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt, model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoriesManager.kt
With the changes in this PR I can successfully run the bulk import on a large model also after the initial import.
=> MODELIX-680 Transfer model data as streams instead of JSON

.github/dependabot.yml
This will keep our model-server image up-to-date.
=> MODELIX-572 Upgrade model-server Docker dependencies with dependabot

mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSLanguageRepository.kt
Extracts changes made to the MPSLanguageRepository class in https://github.com/modelix/modelix.core/pull/482.
=> Enable concept lookup in the MPSLanguageRepository

model-server-openapi/specifications/model-server-html.yaml, model-server/src/main/kotlin/org/modelix/model/server/handlers/ContentExplorer.kt, model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoryOverview.kt
* Adds button to delete a repository
* Provides 'latest' path for content explorer, e.g. `http://127.0.0.1:28101/content/courses/master/latest/`
=> feat(model-server): Minor web UI improvements

model-server/Dockerfile
=> feat(model-server): Add healthcheck to model-server image

bulk-model-sync-gradle-test/build.gradle.kts, bulk-model-sync-gradle-test/src/test/kotlin/org/modelix/model/sync/bulk/gradle/test/ChangeApplier.kt, bulk-model-sync-gradle-test/src/test/kotlin/org/modelix/model/sync/bulk/gradle/test/PullTest.kt, bulk-model-sync-gradle-test/src/test/kotlin/org/modelix/model/sync/bulk/gradle/test/PushTest.kt, bulk-model-sync-gradle-test/test-repo/.mps/modules.xml, bulk-model-sync-gradle-test/test-repo/languages/GraphLang/GraphLang.mpl, bulk-model-sync-gradle-test/test-repo/languages/GraphLang/models/GraphLang.editor.mps, bulk-model-sync-gradle-test/test-repo/languages/GraphLang/models/GraphLang.structure.mps, bulk-model-sync-gradle-test/test-repo/solutions/GraphSolution/models/GraphSolution.example.mps, bulk-model-sync-gradle-test/test-repo/solutions/GraphSolution2/GraphSolution2.msd, bulk-model-sync-gradle-test/test-repo/solutions/GraphSolution2/models/GraphSolution2.example.mps, bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/ModelSyncGradlePlugin.kt, bulk-model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/bulk/ModelImporter.kt, bulk-model-sync-mps/src/main/kotlin/org/modelix/mps/model/sync/bulk/MPSBulkSynchronizer.kt, mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSDevKitDependencyAsNode.kt, mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSJavaModuleFacetAsNode.kt, mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSModuleDependencyAsNode.kt, mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSNode.kt, mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSProjectAsNode.kt, mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSProjectModuleAsNode.kt, mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSSingleLanguageDependencyAsNode.kt
This PR extends the tests for the bulk-sync and contains several fixes.
Among them fixes for [MODELIX-746](https://issues.modelix.org/issue/MODELIX-746) and [MODELIX-747](https://issues.modelix.org/issue/MODELIX-747)
=> MODELIX-756 bulk-model-sync does not import cross-module-references into MPS

model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
According to what is discussed in
https://youtrack.jetbrains.com/issue/KTOR-5286/, use prepareGet instead of Get for all GET requests from model-client that potentially stream the whole model to avoid running into memory issues and NegativeArraySize exceptions.
I was not able to come up with a working tests for this while avoiding to actually use as much memory as MAX_INT bytes. I could reproduce the original issue from MODELIX-785 on my machine and in a local build including this fix, the issue is gone.
=> fix(model-client): use streaming for large responses

model-api-gen-gradle-test/kotlin-generation/src/test/kotlin/org/modelix/modelql/typed/TypedModelQLTest.kt, model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/internal/ModelQLExtensionsGenerator.kt, modelql-typed/src/commonMain/kotlin/org/modelix/modelql/typed/TypedModelQL.kt
see [MODELIX-776](https://issues.modelix.org/issue/MODELIX-776)
=> MODELIX-776 Automatically cast MonoSteps for newly created nodes

bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/tasks/ExportFromModelServer.kt
A replicated model was used that was not disposed. Pulling without continuously replicating is enough.
=> fix(bulk-model-sync): do not use undisposed replicated model

bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/tasks/ImportIntoModelServer.kt
This closes the underlying http client.
=> fix(bulk-model-sync): dispose model client after import into model server

.github/dependabot.yml
=> chore(deps): group typescript-eslint updates

model-client/src/jsMain/kotlin/org/modelix/model/client2/BranchJSImpl.kt, model-client/src/jsMain/kotlin/org/modelix/model/client2/ClientJS.kt, model-client/src/jsTest/kotlin/org/modelix/model/client2/BranchJSTest.kt
This extension of the experimental API will be used by a customer in for a proof of concept.
=> feat(model-client): add function to resolve a node given the node reference on BranchJS

bulk-model-sync-lib/build.gradle.kts
Some long-running tests were failing often, but sometimes they succeed. That's how they made it into master, but many PRs keep failing.
=> MODELIX-802 Flaky test: org.modelix.model.sync.bulk.ModelImporterTest

model-server/src/main/kotlin/org/modelix/model/server/Main.kt, model-server/src/main/kotlin/org/modelix/model/server/handlers/KeyValueLikeModelServer.kt, model-server/src/main/kotlin/org/modelix/model/server/handlers/LightModelServer.kt
Some easy to fix warnings and things in the model-server implementation.
=> Model server code cleanup

metamodel-export/src/main/kotlin/org/modelix/metamodel/export/MPSMetaModelExporter.kt
Also replaced all the other usages of the !! operator in that class.
=> fix(metamodel-export): NPE when a language has no structure aspect

gradle/libs.versions.toml
=> Drop unneeded ktlint plugin from gradle

model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt, model-server/src/main/kotlin/org/modelix/model/server/store/IgniteStoreClient.kt
Fixes [MODELIX-910](https://issues.modelix.org/issue/MODELIX-910).
=> fix(model-client): sort the uploadable objects to avoid freezing the model server

.github/pull_request_template.md
Includes a checklist of things to be verified by authors and reviewers.
Fixes: MODELIX-796
=> chore: add a GitHub PR template

kotlin-utils/src/commonMain/kotlin/org/modelix/kotlin/utils/UnstableModelixFeature.kt
Tries to make clear which content should be put into `intendedFinalization` in `UnstableModelixFeature`.
=> docs: clarify intendedFinalization in UnstableModelixFeature

model-client/src/commonMain/kotlin/org/modelix/model/client2/ReplicatedModel.kt, model-server/src/test/kotlin/org/modelix/model/server/ReplicatedModelTest.kt
Changes needed in modelix to make [MODELIX-630](https://github.com/modelix/modelix.mps-plugins/pull/97) work.
=> Changes in modelix to make MODELIX-630 work

model-server/src/main/kotlin/org/modelix/model/server/Main.kt
Log the cause of internal server errors.
This should help understand internal server errors better.
It gives users the possibility to a stack trace to bug reports.
=> feat(model-server): log the cause of internal server errors

model-api-gen-gradle-test/typescript-generation/package-lock.json, model-api-gen-gradle-test/typescript-generation/src/test-helpers.ts, model-client/src/jsMain/kotlin/org/modelix/model/client2/BranchJSImpl.kt, model-client/src/jsMain/kotlin/org/modelix/model/client2/ClientJS.kt, model-client/src/jsTest/kotlin/org/modelix/model/client2/BranchJSTest.kt, model-client/src/jsTest/kotlin/org/modelix/model/client2/ClientJSTest.kt, vue-model-api/package-lock.json, vue-model-api/src/useModelsFromJson.ts, vue-model-api/src/useRootNode.test.ts, vue-model-api/src/useRootNode.ts
Allow adding custom change handlers to branches in JS
=> feat(model-client): allow adding change handlers to branches in JS

model-client-js-test/replicated-model-test/src/ReplicatedModelJS.test.ts
=> build(model-client): fix failing test in ReplicatedModelJS

.github/workflows/docs.yaml, build.gradle.kts, gradle/libs.versions.toml
This simplifies our API reference setup to increase maintainability.
=> MODELIX-929 API Reference: Only publish latest version

model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoriesManager.kt, model-server/src/main/kotlin/org/modelix/model/server/handlers/ui/RepositoryOverview.kt, model-server/src/test/kotlin/org/modelix/model/server/handlers/RepositoriesManagerTest.kt, model-server/src/test/kotlin/org/modelix/model/server/handlers/ui/RepositoryOverviewTest.kt
This PR also changes the position of the delete button and adds "delete branch"-buttons for non-master branches.
=> MODELIX-781 Add confirmation modal to "delete repository" button

build-logic/build.gradle.kts, build-logic/src/main/kotlin/org/modelix/GenerateVersion.kt, build.gradle.kts, bulk-model-sync-gradle-test/build.gradle.kts, bulk-model-sync-lib/build.gradle.kts, gradle/libs.versions.toml, model-api-gen-gradle-test/kotlin-generation/build.gradle.kts, model-server-lib/src/main/kotlin/org/modelix/model/server/light/LightModelServer.kt, model-server-openapi/specifications/model-server-operative.yaml, model-server/build.gradle.kts, model-server/src/main/kotlin/org/modelix/model/server/Main.kt, model-server/src/main/kotlin/org/modelix/model/server/handlers/AboutApiImpl.kt, model-server/src/main/kotlin/org/modelix/model/server/templates/PageWithMenuBar.kt, model-server/src/test/kotlin/org/modelix/model/server/ModelServerTestUtil.kt, model-server/src/test/kotlin/org/modelix/model/server/handlers/AboutApiTest.kt, modelql-client/src/commonMain/kotlin/org/modelix/modelql/client/ModelQLClient.kt, modelql-core/build.gradle.kts, modelql-core/src/commonMain/kotlin/org/modelix/modelql/core/VersionAndData.kt, modelql-server/src/main/kotlin/org/modelix/modelql/server/ModelQLServer.kt
Show the server version in the endpoint.
Link to the endpoint in the title bar.
=> feat(model-server): add endpoint /about

model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/AccessTrackingStore.kt, model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/CLVersion.kt, model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/PrefetchCache.kt, model-datastructure/src/commonTest/kotlin/org/modelix/model/lazy/PrefetchCacheTest.kt
Implement and fix `PrefetchCache.getAll` methods
=> Implement and fix `PrefetchCache.getAll` methods

model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/PrefetchCache.kt, model-datastructure/src/commonTest/kotlin/org/modelix/model/lazy/PrefetchCacheTest.kt
=> fix(model-datastructure): do not cache `null` values in `PrefetchCache`

model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt, model-client/src/jsMain/kotlin/org/modelix/model/client2/ClientJS.kt, model-server/src/test/kotlin/org/modelix/model/server/ModelClientV2Test.kt
=> fix(model-client): fix typo in setClientProvideUserId

docs/global/modules/core/pages/reference/component-model-server.adoc
=> fix(docs): Fix typo in admin permission name

bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/tasks/ExportFromModelServer.kt, bulk-model-sync-lib/mps-test/build.gradle.kts, bulk-model-sync-lib/mps-test/src/test/kotlin/org/modelix/model/sync/bulk/lib/test/ExportRepositoryTest.kt, bulk-model-sync-lib/src/jvmMain/kotlin/org/modelix/model/sync/bulk/ModelExporter.kt, bulk-model-sync-mps/src/main/kotlin/org/modelix/mps/model/sync/bulk/MPSBulkSynchronizer.kt, gradle/libs.versions.toml
=> MODELIX-784 Clearly state that no module matched the specified conditions when exporting from MPS in the error message

model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt, model-server/src/main/kotlin/org/modelix/model/server/handlers/ui/HistoryHandler.kt, model-server/src/test/kotlin/org/modelix/model/server/handlers/ModelReplicationServerTest.kt
=> MODELIX-993 Requested, but non-existing branch is handled with internal server errors

model-server/src/main/kotlin/org/modelix/model/server/handlers/HttpException.kt, model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt, model-server/src/test/kotlin/org/modelix/model/server/handlers/HttpExceptionTest.kt, model-server/src/test/kotlin/org/modelix/model/server/handlers/ModelReplicationServerTest.kt
Additionally, tested error response in touched code.
Fixes the issue described in https://issues.modelix.org/issue/MODELIX-998
=> fix(model-server): do not use blocking network calls

renovate.json5
Here you can see what updates Renovate would propose: https://github.com/odzhychko/modelix.core/pulls
=>  ci: use Renovate for updating pre-commmit dependencies

modelql-client/src/jvmTest/kotlin/org/modelix/modelql/client/ModelQLClientTest.kt, modelql-untyped/src/commonMain/kotlin/org/modelix/modelql/untyped/ConceptReferenceSetSourceStep.kt, modelql-untyped/src/commonMain/kotlin/org/modelix/modelql/untyped/UntypedModelQL.kt
=> MODELIX-972 Support creating sets of ConceptReference instances in ModelQl

bulk-model-sync-mps/src/main/kotlin/org/modelix/mps/model/sync/bulk/MPSBulkSynchronizer.kt
Use `ThreadUtils.runInUIThreadAndWait` and its return value to do this consistently.
This could be tested by asserting the output of the Gradle task when testing with TestKit.
I did not implement this test straight away for the same reasons described in #982.
I create an issues for us to setup those tests: https://issues.modelix.org/issue/MODELIX-1002
Here is an example output how a thrown Exception is printed in the output:
```
/build/mps/current/lib/3rd-party-rt.jar!/org/slf4j/impl/StaticLoggerBinder.class]
[runMPS] SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
[runMPS] Loading version UmuJe*HakeuG-U1jRuEV4xdLRi1rQSzPlW7uafBxnad8
[runMPS] 2024-08-15 08:34:15,038 [ 216844] SEVERE - j.m.s.ActionDispatcher - Action dispatch failed. Thread AWT-EventQueue-0, …
```
=> fix(bulk-model-sync): propagate all exceptions thrown while running commands in MPS

bulk-model-sync-gradle/build.gradle.kts, bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/ModelSyncGradlePlugin.kt, bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/MpsRunnerConfiguration.kt, bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/config/ModelSyncGradleSettings.kt, bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/tasks/ExportFromModelServer.kt, bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/tasks/ImportIntoModelServer.kt, bulk-model-sync-gradle/src/test/kotlin/org/modelix/model/sync/bulk/gradle/ExportFunctionalTest.kt, bulk-model-sync-gradle/src/test/kotlin/org/modelix/model/sync/bulk/gradle/MpsRunnerConfigurationTest.kt, bulk-model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/bulk/Util.kt, bulk-model-sync-lib/src/commonTest/kotlin/org/modelix/model/sync/bulk/ModuleInclusionTest.kt, bulk-model-sync-mps/src/main/kotlin/org/modelix/mps/model/sync/bulk/IncludedModulesFilter.kt, bulk-model-sync-mps/src/main/kotlin/org/modelix/mps/model/sync/bulk/MPSBulkSynchronizer.kt, docs/global/modules/core/pages/reference/component-bulk-model-sync-gradle.adoc
Aside from the new feature this PR also includes a functional test for the plugin. The already existing tests should be migrated in [MODELIX-1002](https://issues.modelix.org/issue/MODELIX-1002)
=> MODELIX-851 Add option to exclude modules by name in bulk-sync plugin

model-client/build.gradle.kts, model-datastructure/build.gradle.kts
=> remove dependency kotlinx-collections-immutable

gradle/libs.versions.toml, model-api-gen-gradle/build.gradle.kts
=> MODELIX-1015 model-api-gen-gradle unusable in latest releases

model-server/src/main/kotlin/org/modelix/model/server/Main.kt, model-server/src/main/kotlin/org/modelix/model/server/handlers/HttpException.kt, model-server/src/main/kotlin/org/modelix/model/server/handlers/ui/ContentExplorer.kt, model-server/src/main/kotlin/org/modelix/model/server/handlers/ui/DiffView.kt, model-server/src/main/kotlin/org/modelix/model/server/handlers/ui/HistoryHandler.kt, model-server/src/main/kotlin/org/modelix/model/server/templates/PageWithMenuBar.kt, model-server/src/main/resources/public/content-explorer.css, model-server/src/main/resources/public/content-explorer.js, model-server/src/test/kotlin/org/modelix/model/server/handlers/ui/ContentExplorerTest.kt, model-server/src/test/kotlin/org/modelix/model/server/handlers/ui/DiffViewTest.kt
=> MODELIX-1007 Improve comprehensibility of model server history

renovate.json5
The PR by Renovate will look like this: https://github.com/odzhychko/modelix.core/pull/17/files
=> ci: enable updates of the Gradle wrapper with Renovate

model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt, model-client/src/commonTest/kotlin/org/modelix/model/client2/ModelClientV2Test.kt
Adds an option to ModelClientV2Builder to configure the number of retries for failing requests.
=> feat(model-client): make retries configurable

.github/workflows/linting.yml, .spectral.yaml, commitlint.config.js, model-server-openapi/specifications/model-server-v2.yaml, package-lock.json, package.json
Encourages the well-known Zalando RESTful OpenAPI guidelines but doesn't fix all issues. Existing issues are whitelisted (or fixed where easily possible and without breaking). Only new issues would pop up.
=> ci(model-server-openapi): lint the specification with spectral in GHA

model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
This is already done in `putRepositoryObjects`.
In `postRepositoryBranch` this should also be done.
It was not a critical issue because the model client only sent at most 1000 objects to `postRepositoryBranch`. Still, if something blocking happened in Ignite, it might have blocked the request thread.
=> fix(model-server): do not put objects into store in request thread

authorization/src/main/kotlin/org/modelix/authorization/ModelixJWTUtil.kt, authorization/src/main/kotlin/org/modelix/authorization/permissions/AccessControlData.kt, authorization/src/test/kotlin/org/modelix/authorization/RSATest.kt, model-server/src/main/kotlin/org/modelix/model/server/DBAccessControlPersistence.kt
fix(authorization): verification against private keys from disk failed
=> fix(authorization): verification against private keys from disk failed

model-client/src/jvmMain/kotlin/org/modelix/model/oauth/ModelixAuthClient.kt
OAuth providers usually require you to configure valid redirect URLs. With random ports the redirect URL cannot be known in advance. The OAuth client now uses the first available port in the range 26815-26914.
It's probably not necessary to configure all 100 URLs, but if you every experience many unavailable ports, just add one more URL.
=> feat(model-client): use known port in PKCE redirect URL

model-client/src/jvmMain/kotlin/org/modelix/model/oauth/ModelixAuthClient.kt, mps-sync-plugin3/src/main/kotlin/org/modelix/mps/sync3/BindingWorker.kt
Sometimes the plugin just shows "disconnected", but there is no log output that explains why it doesn't connect.
=> More log output for the sync plugin

model-client/src/jvmMain/kotlin/org/modelix/model/oauth/ModelixAuthClient.kt
=> fix(model-client): don't forget old refresh tokens during refresh_token grant
