modelix/modelix.core

- metamodel-export-mps/build.gradle.kts
- settings.gradle
Uses the `plugins {}` DSL to declare the mpsbuild plugin dependency.
In order to make repositories apart from the default `gradlePluginPortal()` available, they have to specified in the pluginManagement inside of `settings.gradle`.
closes #46
> Simplify mpsbuild plugin dependency

- .github/workflows/publish.yml
- .github/workflows/release.yml
This PR migrates the release steps to a personal access token to ensure that the publish pipeline is triggered on new release tags as discussed in: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow
The ci changes are marked as a `fix` commit to trigger a functional release once.
> Ensure new releaes trigger artifact publishing

- build.gradle.kts
- gradle.properties
- kotlin-js-store/yarn.lock
- metamodel-gradle-test/build.gradle.kts
- metamodel-runtime/build.gradle.kts
- model-api/build.gradle.kts
- model-client/build.gradle.kts
- settings.gradle.kts
The Kotlin 1.7 gradle plugin throws some exception when there are failing tests, which shadows the reporting of the failed tests. Kotlin 1.8 seems to work better with Gradle 8.
> feat: use kotlin 1.8 and also bump all other dependencies

- light-model-client/src/commonMain/kotlin/org/modelix/client/light/LightModelClient.kt
- light-model-server/src/main/kotlin/org/modelix/model/server/light/LightModelServer.kt
- metamodel-runtime/src/commonMain/kotlin/org/modelix/metamodel/GeneratedConcept.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/INode.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/IRole.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/ITransaction.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/ITree.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/PBranch.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/PNodeAdapter.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/SimpleChildLink.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/SimpleConcept.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/SimpleProperty.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/SimpleReferenceLink.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/TreePointer.kt
- model-client/src/commonMain/kotlin/org/modelix/model/lazy/CLTree.kt
- model-client/src/commonMain/kotlin/org/modelix/model/metameta/MetaModelBranch.kt
- model-client/src/commonMain/kotlin/org/modelix/model/persistent/CPTree.kt
- model-client/src/commonTest/kotlin/org/modelix/model/TreeSerializationTest.kt
- model-server-api/src/commonMain/kotlin/org/modelix/model/server/api/VersionData.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/LightModelServer.kt
First step towards using IDs instead of names when storing children/properties/references.
It's backward compatible. Existing models on the model server keep using names, new models will use IDs.
INode.name returns the name or the UID depending on the context it is executed in. Existing code will continue to work, but should be migrated eventually.
> MODELIX-361 models can store role UIDs instead of names

- metamodel-export-mps/build.gradle.kts
It was automatically generated by the mpsbuild plugin, but is not required and was never used.
> disabled the "org.modelix:all" publication

- .github/workflows/release.yml
For authorization the checkout action uses the GITHUB_TOKEN by default.
This prevents the publish pipeline to be triggered by the tag created by semantic release.
Now the personal access token is used instead.
> MODELIX-402: Publish pipeline in modelix.core doesn't run on releases

- metamodel-generator/build.gradle.kts
- model-client/build.gradle.kts
IModelClientV2 uses ModelQuery as a parameter which requires this dependency to be of type 'api'.
> model-server-api has to be an api dependency in model-client

- ts-model-api/package.json
the provided file does not exist and consequently results in vite throwing an error
> fix: module import for vite

- .github/workflows/docs.yaml
- build.gradle.kts
- dokka/logo-dark.svg
- dokka/logo-styles.css
- gradle.properties
This sets up automatic api reference generation using Dokka.
The docs are generated and published to GitHub pages in a GitHub workflow, which is triggered by new major and minor releases.
Additionally docs can be generated locally by running `./gradlew dokkaHtmlMultiModule` in the root directory of the project.
> MODELIX-429: Automatic API reference generation

- .github/workflows/docs.yaml
- build.gradle.kts
Fixes the copyright symbol not being shown on the index page.
Fixes the index page only listing the newest version.
> Fixes for API reference index page

- build.gradle.kts
Gradle supports to publish version catalogs and consume them in other projects. This might an alternative to the "platform" for aligning dependencies with the used modelix.core version.
This publishes a new artifact. We have to agree on a name for that. Suggestions are welcome.
> feat: publish version catalog

- model-server-lib/src/main/kotlin/org/modelix/model/server/light/QueryImplementation.kt
Restore the old behavior of allow to query non-existing children similar to what has been done in MODELIX-435 for references.
Fixes: #MODELIX-444
> fix(model-server-lib): don't throw exceptions for missing children

- model-api/src/commonMain/kotlin/org/modelix/model/api/ConceptUtil.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/IBranch.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/IBranchListener.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/IChildLink.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/IConcept.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/IConceptReference.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/IIdGenerator.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/ILanguage.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/ILanguageRepository.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/ILink.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/INode.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/INodeReference.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/INodeReferenceSerializer.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/INodeWrapper.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/IProperty.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/IReadTransaction.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/IReferenceLink.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/IRole.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/ITransaction.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/ITree.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/ITreeChangeVisitor.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/ITreeChangeVisitorEx.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/IWriteTransaction.kt
This adds basic documentation to the interfaces of the model api.
It should be considered as a starting point and the information should be verified before merging.
> MODELIX-419 Add documentation for model api reference

- metamodel-export/org.modelix.metamodel.export/models/org.modelix.metamodel.export.mps
- metamodel-export/org.modelix.metamodel.export/org.modelix.metamodel.export.msd
- model-api-gen-gradle-test/build.gradle.kts
- model-api-gen-gradle-test/src/test/kotlin/GeneratedApiTest.kt
- model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/GeneratorInput.kt
- model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/MetaModelGenerator.kt
- model-api/src/commonMain/kotlin/org/modelix/model/data/MetaModelData.kt
Deprecations from MPS are propagated to the corresponding generated ConceptWrapperInterface (or its members).
The test for this might break if the referenced deprecations are removed from baseLanguage in the future.
I'm open to suggestions on how to make the test easier to maintain.
> MODELIX-455 Transfer MPS deprecations to generated Kotlin code

- model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/TypescriptMMGenerator.kt
Follow-up bugfix for https://github.com/modelix/modelix.core/pull/144 in collaboration with @abstraktor.
> fix(model-api-gen): Add missing parentheses for getter method declarations and definitions. Fix null-safe unwrap method call.

- model-client/src/jvmMain/kotlin/org/modelix/model/client/RestWebModelClient.kt
The RestWebModelClient has a hard-coded 1 seconds connection timeout in its constructor. This timeout cannot be influenced from the outside, but it makes our tests fail. This PR increases the timeout to 30 seconds, which might be better.
A better fix of this problem would be if RestWebModelClient would take into consideration the timeout values coming from `providedClient`, if it makes sense.
> Increase default connection timeout

- model-server/src/main/kotlin/org/modelix/model/server/store/ClientIdProcessor.kt
This MR fixes a NumberFormatException that may occur if the String does not represent a Long value (e.g. overflown Long, a String that has nothing to do with a Long number, etc.). The fix is the same as how String is parsed to Long in the [InMemoryStoreClient.generateId](https://github.com/modelix/modelix.core/blob/main/model-server/src/main/kotlin/org/modelix/model/server/store/InMemoryStoreClient.kt#L82) method.
> NumberFormatException in ClientIdProcessor

- build.gradle.kts
- gradle/libs.versions.toml
After merging this and a new deployment triggered by the next minor release, the ordering will be fixed automatically.
> MODELIX-465 Ordering of versions in the generated API Reference Landing Page is broken

- build.gradle.kts
This hopefully helps tools such as dependabot or renovate to pick up changelog information from the repo.
> build: include SCM and URL Maven metadata in generated POMs

- docs/global/modules/core/pages/howto/testing-against-model-api.adoc
- docs/global/modules/core/partials/nav-howto.adoc
Adds a how-to entry for local testing with a local branch.
> docs(model-api): explain local testing

- model-server/src/main/kotlin/org/modelix/model/server/store/ClientIdProcessor.kt
- model-server/src/main/kotlin/org/modelix/model/server/store/InMemoryStoreClient.kt
As a follow-up of https://github.com/modelix/modelix.core/pull/162, I implemented an ID generator that is null and Long range safe. It increments the parameter ID by one. If the input parameter is null, 0, not a Long number or equals to Long.MAX_VALUE, then it replaces it with 0L. This way, we can be sure that the resulting ID is always a positive Long number that is at most Long.MAX_VALUE.
The generator is a function that is used both in ClientIdProcessor and InMemoryStoreClient to avoid double maintenance efforts.
> Long range safe ID generator

- .github/workflows/build.yaml
Only trigger builds on PRs and not also on every push to avoid building twice.
Fixes: MODELIX-471
> ci: avoid duplicate builds in PRs

- model-server/src/main/kotlin/org/modelix/model/server/CmdLineArgs.kt
- model-server/src/main/kotlin/org/modelix/model/server/Main.kt
Adds -h and --help to the model-server CLI.
> feat(model-server): add an online help for command line arguments

- .github/workflows/mps-model-adapters.yaml
- mps-model-adapters/build.gradle.kts
- mps-model-adapters/src/main/java/org/modelix/model/mpsadapters/ConceptWorkaround.java
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSConcept.kt
It's actually just an issue of the Kotlin compiler and the bytecode would have been compatible.
It's still good to have the workflow that detects possible incompatibilities.
> mps-model-adapters: fixed incompatibility with MPS 2021.2

- build.gradle.kts
The version catalog was only published to maven-local, because there was no publishing repository specified for the root project.
> fix: version catalog wasn't published

- docker-build-model.sh
Also updated the description at
https://hub.docker.com/repository/docker/modelix/modelix-model/general
The old tag is still published to avoid breaking existing projects, but new projects should use the new name.
At least our helm chart should be updated soon: https://github.com/modelix/modelix/blob/46bf6ccb902050ae7035ef07b81bb4180213a66c/helm/modelix/templates/common/model-deployment.yaml#L31
> fix: MODELIX-481 rename docker image modelix/modelix-model to modelix/model-server

- light-model-client/build.gradle.kts
Converts the implementation dependency of light-model-client on modelql-untyped into an api dependency as the base class of a LightModelClient instance is part of that package. Otherwise, downstream projects might fail to build due to being unable to resolve the base class.
Fixes: MODELIX-496
> fix(light-model-client): expose modelql-untyped as a dependency

- build.gradle.kts
Ensures that the compiled code is compatible with older versions of Kotlin.
In the modelix.samples project this fixes an incompatibility with the Kotlin version used by Quarkus (1.7).
> fix: set Kotlin API Version to 1.6

- model-server-lib/src/main/kotlin/org/modelix/model/server/light/LightModelServer.kt
- model-server/src/main/kotlin/org/modelix/model/server/Main.kt
> The existing timeouts sometimes caused disconnects when requesting larger amounts of data despite everything being functional.
see. #208 
Make the LightModelServer in the model server behave more robust and more alike to the LightModelServer in MPS.
> fix(model-server): configure websockets connections to be more robust

- modelql-core/src/commonMain/kotlin/org/modelix/modelql/core/ZipElementAccessStep.kt
- modelql-core/src/commonMain/kotlin/org/modelix/modelql/core/ZipStep.kt
- modelql-core/src/commonTest/kotlin/org/modelix/modelql/core/ModelQLTest.kt
With these additions, zip output can be used with kotlin destructing declarations:
```kotlin
foo.zip(bar).map { (theFoo, theBar) -> ... }
foo.zip(bar).mapLocal { (theFoo, theBar) -> ... }
```
> feat(modelql): support destructing zip output

- modelql-core/src/commonMain/kotlin/org/modelix/modelql/core/ZipElementAccessStep.kt
- modelql-core/src/commonMain/kotlin/org/modelix/modelql/core/ZipStep.kt
Remove the typo. Old methods are still available but deprecated for now.
> fix(modelql): rename zip accessor forth -> fourth

- modelql-client/src/commonMain/kotlin/org/modelix/modelql/client/ModelQLNode.kt
- modelql-client/src/jvmTest/kotlin/org/modelix/modelql/client/ModelQLClientTest.kt
> fix(modelql): access to references outside of queries

- model-client/src/commonMain/kotlin/org/modelix/model/client2/Closable.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/IModelClientV2.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- model-client/src/jsMain/kotlin/org/modelix/model/client2/Closable.js.kt
- model-client/src/jvmMain/kotlin/org/modelix/model/client2/Closable.jvm.kt
- model-client/src/jvmTest/kotlin/org/modelix/model/client2/ModelClientV2JvmTest.kt
Do not depend on Ktor utils.
Just provide a close method.
Closable is only a concept on the JVM.
> fix(model-client): change wrong dependency to Closable

- model-server/src/test/kotlin/org/modelix/model/server/ReplicatedRepositoryTest.kt
- modelql-client/src/commonMain/kotlin/org/modelix/modelql/client/ModelQLNode.kt
- modelql-core/src/commonMain/kotlin/org/modelix/modelql/core/FirstElementStep.kt
- modelql-core/src/commonMain/kotlin/org/modelix/modelql/core/IStep.kt
- modelql-core/src/commonMain/kotlin/org/modelix/modelql/core/IStepOutput.kt
- modelql-core/src/commonMain/kotlin/org/modelix/modelql/core/MapIfNotNullStep.kt
- modelql-core/src/commonMain/kotlin/org/modelix/modelql/core/TransformingStepWithParameter.kt
- modelql-core/src/commonMain/kotlin/org/modelix/modelql/core/ZipElementAccessStep.kt
- modelql-core/src/commonTest/kotlin/org/modelix/modelql/core/ModelQLTest.kt
There was a mismatch between the elements returned by `ZipElementAccessStep.createFlow` and what the serializer of `ZipElementAccessStep.getOutputSerializer` could handle. `ZipElementAccessStep` doesn't implement it's own serializer, but forwards the serializer and the elements of the step that produced the zip input.
The bug was that `ZipElementAccessStep` didn't forward the `IStepOutput`, but unwrapped it and rewrapped into a new `SimpleStepOutput`, because that's the default behavior of the super class `MonoTransformingStep`.
> fix(modelql): CCE from SimpleStepOutput to MultiplexedOutput

- bulk-model-sync-lib/build.gradle.kts
- kotlin-utils/build.gradle.kts
- light-model-client/build.gradle.kts
- model-api-gen-runtime/build.gradle.kts
- model-api/build.gradle.kts
- model-client/build.gradle.kts
- model-datastructure/build.gradle.kts
- model-server-api/build.gradle.kts
- modelql-client/build.gradle.kts
- modelql-core/build.gradle.kts
- modelql-html/build.gradle.kts
- modelql-typed/build.gradle.kts
- modelql-untyped/build.gradle.kts
Source set access in multi-platform projects is expected to happen by delegation. Yet, the created vals are usually not accessed afterwards and result in compilation warnings when Gradle compiles the build file.
This commit adds suppressions for these warnings. As IntelliJ understands these warnings as unneeded, despite having an effect on command-line compilation, another suppression for the unneeded suppressions is needed.
Cf.: https://youtrack.jetbrains.com/issue/KT-38871
> build: suppress warnings from unused variables for source sets

- modelql-client/src/jvmTest/kotlin/org/modelix/modelql/client/HtmlBuilderTest.kt
The timeout was a bit tight for execution on github actions and failed sometimes.
> test: increased timeout in HtmlBuilderTest

- modelql-core/src/commonMain/kotlin/org/modelix/modelql/core/IStepOutput.kt
- modelql-untyped/src/commonMain/kotlin/org/modelix/modelql/untyped/ResolveNodeStep.kt
The error message was just `java.lang.IllegalArgumentException: Node not found: org.modelix.modelql.core.SimpleStepOutput@4ac2d1e8` which makes it hard to debug.
> fix(modelql): error message for failed node resolution didn't contain the reference

- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSNodeReference.kt
They contained only the node ID instead of the whole reference:
`mps:741118295176715139`
instead of
`mps:r:54d7f6a3-9a78-48d5-97cc-b47cbb1f005c(my.model)/741118295176715139`
> MODELIX-549 incorrect serialization of MPS node references

- model-client/src/commonMain/kotlin/org/modelix/model/client2/IModelClientV2.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ReplicatedModel.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/LinearHistory.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/VersionMerger.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/operations/OTBranch.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/persistent/MapBasedStore.kt
- model-server/build.gradle.kts
- model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoriesManager.kt
- model-server/src/test/kotlin/org/modelix/model/server/ReplicatedRepositoryTest.kt
The reason that the test failed sometimes was that each replica kept creating new merge commits after receiving an update, causing the history to grow without any actual change to the model. The complexity of the merge operation also kept growing and at some point the algorithm just took to long and the synchronization didn't finish within the time limit.
> MODELIX-524 unstable ReplicatedRepositoryTest

- model-client/src/commonMain/kotlin/org/modelix/model/client2/IModelClientV2.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- model-client/src/jvmMain/kotlin/org/modelix/model/client/RestWebModelClient.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/LinearHistory.kt
- model-datastructure/src/commonTest/kotlin/LinearHistoryTest.kt
- model-server/src/main/kotlin/org/modelix/model/server/Main.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/KeyValueLikeModelServer.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoriesManager.kt
- model-server/src/test/java/org/modelix/model/server/RestModelServerTest.java
- model-server/src/test/kotlin/org/modelix/model/server/ModelClientTest.kt
- model-server/src/test/kotlin/org/modelix/model/server/ReplicatedRepositoryTest.kt
- model-server/src/test/resources/functionaltests/storing.feature
The old REST API now also uses the RepositoriesManager to write to branches in a safe way (in a transaction with conflict resolution) instead of just overwriting the existing value. A write to a key that matches the branch pattern is dispatched to the RepositoriesManager and not written directly to the key-value store anymore.
While trying to make the tests succeed I had to fix a few issues, especially a performance issue in LinearHistory that also was another reason for MODELIX-524.
There is a new test that writes concurrently using the old and new client. Some of the iterations always fail which is probably a bug in the old model-client. I disabled the test for now and will fix that in a separate PR ([MODELIX-554](https://issues.modelix.org/issue/MODELIX-554/Unstable-ModelClient-v1)).
> MODELIX-514 Make changes from the MPS model sync plugin visible to the ModelClientV2

- kotlin-utils/src/commonMain/kotlin/org/modelix/kotlin/utils/DeprecationInfo.kt
The annotation `@DeprecationInfo` makes it possible to record since when a `@Deprecated` annotation is in place and what needs to be considered before removing the affected code.
Extending `@Deprecated` to record this information wasn't possible as the class is not open.
> chore: add an annotation to record deprecation meta data

- model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/CLTree.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/persistent/CPHamtNode.kt
- model-datastructure/src/commonTest/kotlin/DiffTest.kt
This fixes the case tested by `DiffTest.moveChildInsideNode`.
The problem was, that when a child node moved inside its parent node, the changed was not propagated to the visitor.
Moving a child inside a node is equivalent to changing the role of the child node in the parent.
`DiffTest.moveChildOutsideNode` works without the fix and was added for completeness.
---
Locally, this change makes sense. But I'm not sure about the global implications.
> fix(model-datastructure): detect changed children in a node if a child node changes its role

- .detekt.yml
- .github/workflows/build.yaml
- build.gradle.kts
- gradle/libs.versions.toml
This PR includes [detekt](https://detekt.dev/docs/intro/) as a linter in the project. In contrast to ktlint, detect is more focused on coding problems and might provide some valuable hints. I have disable failing the build when detekt issues exist due to the current amount of violations that already exist in the current code base.
Detekt results are passed into the GitHub Code Scanning feature. Effectively this means that PRs will receive inline annotations for detected problems and we can use these as a hint when reviewing PRs.
> ci: include detekt with GitHub code security analysis

- .github/workflows/mps-compatibility.yaml
This makes the workflow file more concise and also has the benefit of parallel execution on multiple runners, thereby avoiding the blown up disk space issue due to having all MPS versions on the disk in the same job.
> ci: convert the MPS compatibility workflow to a matrix strategy

- .github/workflows/build.yaml
- .github/workflows/mps-compatibility.yaml
- .github/workflows/publish.yml
This adapts the way gradle-build-action is used in our workflow definition to the current recommended practice:
https://github.com/marketplace/actions/gradle-build-action#use-the-action-to-setup-gradle
Follow-up for the discussions in https://github.com/modelix/modelix.core/pull/284
> ci: use gradle-build-action for setting up Gradle

- bulk-model-sync-gradle-test/src/test/kotlin/org/modelix/model/sync/bulk/gradle/test/PushTest.kt
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/tasks/ImportIntoModelServer.kt
- bulk-model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/bulk/ModelImporter.kt
- bulk-model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/bulk/Util.kt
- bulk-model-sync-lib/src/jvmMain/kotlin/org/modelix/model/sync/bulk/PlatformSpecific.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ReplicatedModel.kt
This PR fixes the issue, that imported models don't show up in the model-server.
Instead of using ReplicatedModel, which is intended for real-time collaboration (and doesn't seem to be able to handle the huge amount of changes that happen during the bulk sync), a new `runWrite` function is used to push the changes to the server.
By calling this method inside of `runBlocking` it is ensured, that the changes have been successfully pushed to the model-server.
> MODELIX-561 Import into model-server is unsuccessful

- model-server/Dockerfile
Vulnerability report of the [new](https://catalog.redhat.com/software/containers/ubi8/openjdk-11/5dd6a4b45a13461646f677f4?architecture=amd64&image=651ef9c1cb96549bcc6abc38&container-tabs=security) vs. [previous](https://catalog.redhat.com/software/containers/ubi8/openjdk-11/5dd6a4b45a13461646f677f4?architecture=amd64&image=649348c8e97f8bf5eeed4680) images.
> chore(model-server): update base image to reduce vulnerabilities

- model-server/src/main/kotlin/org/modelix/model/server/handlers/ContentExplorer.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/ContentExplorerExpandedNodes.kt
- model-server/src/main/resources/public/content-explorer.js
Instead of loading the whole model when a repository is selected only the root node is loaded. 
Nodes on next levels are loaded when their parent node is expanded.
The Expand All button doesn't load the whole tree any more, but it expands one more level in the Content Explorer.
> MODELIX-399 Lazy loading for the content explorer

- model-client/build.gradle.kts
- model-client/src/commonMain/kotlin/org/modelix/model/client2/IModelClientV2.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- model-server/build.gradle.kts
- model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
- model-server/src/test/kotlin/org/modelix/model/server/ModelClientV2Test.kt
The endpoint was already implemented on the server side, but there was no method on the client side to call it.
> MODELIX-577 Add ModelQL v2 support to model-server

- build.gradle.kts
- bulk-model-sync-gradle-test/build.gradle.kts
- bulk-model-sync-gradle-test/graph-lang-api/build.gradle.kts
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/ModelSyncGradlePlugin.kt
- docs/global/modules/core/pages/howto/usage-model-api-gen-gradle.adoc
- docs/global/modules/core/pages/reference/component-bulk-model-sync-gradle.adoc
- model-api-gen-gradle/src/main/kotlin/org/modelix/metamodel/gradle/MetaModelGradlePlugin.kt
- model-api/build.gradle.kts
- model-client/build.gradle.kts
- model-server/build.gradle.kts
- modelql-core/build.gradle.kts
- mps-model-server-plugin/build.gradle.kts
- ts-model-api/build.gradle.kts
Replace the usage of `Project.buildDir` in our build scripts and in our provided plugins.
See https://docs.gradle.org/current/userguide/upgrading_version_8.html#deprecations_2
> replace deprecated Project.buildDir usage in Gradle 

- bulk-model-sync-gradle-test/src/test/kotlin/org/modelix/model/sync/bulk/gradle/test/PullTest.kt
- bulk-model-sync-gradle-test/src/test/kotlin/org/modelix/model/sync/bulk/gradle/test/PushTest.kt
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/ModelSyncGradlePlugin.kt
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/config/ModelSyncGradleSettings.kt
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/tasks/GenerateAntScriptForMps.kt
- bulk-model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/bulk/ModelImporter.kt
- bulk-model-sync-solution/solutions/org.modelix.mps.model.sync.bulk/org.modelix.mps.model.sync.bulk.msd
- docs/global/modules/core/pages/reference/component-bulk-model-sync-gradle.adoc
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSNode.kt
The issue here was two-fold:
1. There was a missing dependency in `bulk-model-sync-solution`
2. The INodeResolutionScope was not set
While looking for the exact issues, I found it useful to have the ability to debug the headless MPS in the bulk-sync plugin remotely. That's why this PR also includes a new feature, which enables users to turn on remote debugging for MPS by specifying a port.
> MODELIX-587 IllegalStateException when syncing references

- docs/global/modules/core/pages/reference/component-vue-model-api.adoc
- docs/global/modules/core/partials/nav-reference.adoc
Add minimal docs about Vue.js bindings to the reference docs, for them to be visible in the docs of the upcoming release.
Ideas for more comprehensive and useful documentation are recorded in https://issues.modelix.org/issue/MODELIX-599
> docs(vue-model-api): add minimal reference docs

- bulk-model-sync-lib/build.gradle.kts
- kotlin-utils/build.gradle.kts
- light-model-client/build.gradle.kts
- model-api-gen-runtime/build.gradle.kts
- model-api/build.gradle.kts
- model-client/build.gradle.kts
- model-datastructure/build.gradle.kts
- model-server-api/build.gradle.kts
- modelql-client/build.gradle.kts
- modelql-core/build.gradle.kts
- modelql-html/build.gradle.kts
- modelql-typed/build.gradle.kts
- modelql-untyped/build.gradle.kts
The suppression was relevant for false warnings, which are now fixed.
Cf. https://issues.modelix.org/issue/MODELIX-544
> build: remove unneeded suppress warnings

- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/ModelSyncGradlePlugin.kt
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/config/ModelSyncGradleSettings.kt
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/tasks/ImportIntoModelServer.kt
- bulk-model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/bulk/ModelImporter.kt
- docs/global/modules/core/pages/reference/component-bulk-model-sync-gradle.adoc
With the new option, the sync can ignore errors encountered during syncing instead of immediately terminating. This is some sort of graceful degradation at the cost of potentially resulting in an inconsistent sync.
I'll add the missing implementation for the direction towards MPS after #312 is merged to avoid unnecessary conflicts.
> feat(bulk-model-sync-gradle): add continueOnError option

- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/config/ModelSyncGradleSettings.kt
This option was not used at all and also not documented. Therefore, we might find it ok that this is not a breaking change.
> chore(bulk-model-sync-gradle): remove unused mpsDebugEnabled option

- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSModelAsNode.kt
If an imported model could not be resolved, it caused a `NullPointerException`. 
This change handles this case gracefully.
> fix(mps-model-adapters): handle unresolvable model imports

- docs/global/modules/core/pages/reference/component-mps-model-server-plugin.adoc
- model-server-lib/src/main/kotlin/org/modelix/model/server/light/LightModelServer.kt
- mps-model-server-plugin/src/main/kotlin/org/modelix/model/server/mps/MPSModelServer.kt
New health check `loadModels` implemented. Multiple `moduleNamespace` parameters can be provided to specify the relevant modules.
> MODELIX-608 Health check for warming up the MPS cache

- model-client/src/jvmMain/kotlin/org/modelix/model/client/RestWebModelClient.kt
- model-client/src/jvmMain/kotlin/org/modelix/model/client/VersionChangeDetector.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/IKeyValueStore.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoriesManager.kt
VersionChangeDetector wasn't disposed, while waiting for a change.
It was transitively calling runBlocking from a coroutine which means a
cancellation of the coroutine has no effect while being blocked.
> fix(model-client): memory leak in VersionChangeDetector

- light-model-client/src/commonMain/kotlin/org/modelix/client/light/LightModelClient.kt
Implementing `IStateVariableGroup` but not exposing `org.modelix.incremental` as API dependency resulted in the following error when using the light-model-client library: Cannot access 'org.modelix.incremental.IStateVariableGroup' which is a super type of 'org.modelix.client.light.LightModelClient'. Check your module class path for missing or conflicting dependencies.
Exposing `org.modelix.incremental` as an API dependency would have been a solution too, but we should not expose its API accidentally. When consumers want to use the light-model-client with its incremental functionality, they should add `org.modelix.incremental` as a dependency themselves.
Fixes https://github.com/modelix/modelix.samples/pull/205
> fix(light-model-client): Do implement `org.modelix.incremental` interfaces in public classes

- .github/workflows/dry-run-release.yml
- .github/workflows/release.yaml
We want to release nightly, instead of after each merged PR to avoid spamming releases.
For urgent cases, the workflow can still be dispatched manually.
> MODELIX-655 Convert release to nightly

- .github/workflows/publish.yml
An increased timeout might reduce failing uploads that are caused by slow or unstable connections.
> ci: increase HTTP timeout in Gradle for publishing

- .gitignore
- commitlint.config.js
- model-server/build.gradle.kts
- model-server/src/main/kotlin/org/modelix/model/server/Main.kt
- model-server/src/main/kotlin/org/modelix/model/server/store/IStoreClient.kt
- model-server/src/main/kotlin/org/modelix/model/server/store/IgniteStoreClient.kt
- model-server/src/main/kotlin/org/modelix/model/server/store/InMemoryStoreClient.kt
- model-server/src/main/resources/org/modelix/model/server/store/ignite-inmemory.xml
- model-server/src/test/kotlin/org/modelix/model/server/StoreClientTest.kt
Ignite doesn't support nested transactions. Starting a transaction from inside a transaction throws the following exception:
```
java.lang.IllegalStateException: Failed to start new transaction (current thread already has a transaction): ...
at org.apache.ignite.internal.processors.cache.transactions.IgniteTransactionsImpl.txStart0(IgniteTransactionsImpl.java:184)
at org.apache.ignite.internal.processors.cache.transactions.IgniteTransactionsImpl.txStart(IgniteTransactionsImpl.java:70)
at org.modelix.model.server.store.IgniteStoreClient.runTransaction(IgniteStoreClient.kt:139)
at org.modelix.model.server.handlers.RepositoriesManager.mergeChanges(RepositoriesManager.kt:151)
at org.modelix.model.server.handlers.KeyValueLikeModelServer$putEntries$1.invoke(KeyValueLikeModelServer.kt:323)
at …
```
> fix(model-server): writing to a branch using the v1 API failed

- bulk-model-sync-gradle-test/ci.sh
Waiting was flakey and the POST is no longer needed as MODELIX-615 has been resolved.
> ci(bulk-model-sync-gradle): replace sleep with health-check

- bulk-model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/bulk/ModelImporter.kt
- bulk-model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/bulk/Util.kt
- bulk-model-sync-lib/src/jsMain/kotlin/org/modelix/model/sync/bulk/Utils.kt
- bulk-model-sync-lib/src/jvmMain/kotlin/org/modelix/model/sync/bulk/Utils.kt
- bulk-model-sync-lib/src/jvmTest/kotlin/org/modelix/model/sync/bulk/ProgressReporterTest.kt
The implemented progress reporting in the ModelImporter always used carriage returns to report progress. This only works in terminals and breaks incremental logging in setups like k8s.
This commit tries to detect if running in a terminal and if not, resorts to logging calls for progress reporting. Logging output is reduced to avoid excessive spam in captured log file.
> fix(bulk-model-sync-lib): use carriage returns only on TTYs

- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/tasks/ImportIntoModelServer.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
Makes previously hard-coded HTTP timeouts for the model client configurable and increases the timeout for the bulk sync, where we see timeouts hitting with large models.
> Configure HTTP timeouts in bulk sync.

- .github/workflows/release.yaml
While the schedule trigger only works on the default branch, the workflow_dispatch trigger can still be run on other branches. This is a precaution to not accidentally run it on a different branch.
> ci: restrict release workflow to main

- ts-model-api/build.gradle.kts
The old pattern only included the directory `dist` without its content.
> fix(ts-model-api): publish the contents of the `dist` directory

- .pre-commit-config.yaml
- commitlint.config.js
- model-server/src/main/kotlin/org/modelix/model/server/handlers/KeyValueLikeModelServer.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoriesManager.kt
- model-server/src/test/kotlin/org/modelix/model/server/ModelClientTest.kt
Clients using the v1 API expect server ID to be set.
See https://github.com/modelix/modelix.mps-plugins/blob/70293ee28914c4c5987f0cd67a500806a8a26411/mps-legacy-sync-plugin/src/main/java/org/modelix/model/mpsplugin/ModelServerConnection.kt#L168
See `ModelServerConnection#onConnect` in https://github.com/modelix/modelix.mps/blob/c594b1cc45222a3e8860d1bfb6468cd5bbb1bb77/mps/org.modelix.model.mpsplugin/models/org.modelix.model.mpsplugin.mps
> fix: initialize the server ID

- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/ModelSyncGradlePlugin.kt
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/config/ModelSyncGradleSettings.kt
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/tasks/ExportFromModelServer.kt
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/tasks/ImportIntoModelServer.kt
- docs/global/modules/core/pages/reference/component-bulk-model-sync-gradle.adoc
Depending on the size of the model, the import into the model-server might have some long-running HTTP calls. As the default timeout was not sufficient in all cases, it can now be configured by users of the task.
> feat(bulk-model-sync-gradle): make request timeout configurable

- .github/workflows/publish.yml
To find out why publishing sporadically fails, this commit enabled Gradle info logging in the publish workflow. Gradle would log HTTP request retries on this level and maybe they are the source of our sporadic redeployment issues. Info level should be safe to stay enabled as it does not leak credentials or something else.
> ci: enable info logging in publish workflow as a debugging aid

- model-server/Dockerfile
This follows best practices for Docker images.
> You can use the exec form of ENTRYPOINT to set fairly stable default commands and arguments and then use either form of CMD to set additional defaults that are more likely to be changed.
See https://docs.docker.com/engine/reference/builder/#exec-form-entrypoint-example
Using a ENTRYPOINT in model-server docker container makes passing arguments easier.
For example,
`docker run modelix/model-server ./run-model-server.sh -inmemory`
would be simplified to
`docker run modelix/model-server -inmemory`
BREAKING CHANGE: The previous entry point was the default `ENTRYPOINT ["/bin/sh", "-c"]`.
Now it is `ENTRYPOINT ["./run-model-server.sh"]`.
If you used `docker run modelix/model-server ./run-model-server.sh <args>` to pass arguments,
you now have to …
> feat(model-server)!: Use ENTRYPOINT instead of CMD in the provided Docker image

- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/ModelSyncGradlePlugin.kt
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/config/ModelSyncGradleSettings.kt
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/tasks/ImportIntoModelServer.kt
- docs/global/modules/core/pages/reference/component-bulk-model-sync-gradle.adoc
Registering is not needed for the sync as only the untyped api is used.
> fix(bulk-model-sync-gradle): deprecate registerLanguage

- model-api-gen-gradle-test/kotlin-generation/src/test/kotlin/org/modelix/modelql/typed/TypedModelQLTest.kt
- model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/GeneratorInput.kt
- model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/MetaModelGenerator.kt
- modelql-typed/src/commonMain/kotlin/org/modelix/modelql/typed/TypedModelQL.kt
Adds the ability to perform write operations in ModelQL queries.
As the MetaModelGenerator class has organically grown to a significant size, [MODELIX-667](https://issues.modelix.org/issue/MODELIX-667) was created as a followup ticket.
> MODELIX-644 Support writing in generated typed API with ModelQl

- model-server/src/main/kotlin/org/modelix/model/server/handlers/DeprecatedLightModelServer.kt
- model-server/src/test/kotlin/org/modelix/model/server/JsonAPITest.kt
The WebSocket was accidentally moved to /{repositoryId}/ws while refactoring in 672d329.
> fix(model-server): restore WebSocket endpoint /json/{repositoryId}/ws

- .github/dependabot.yml
followup for #403 as dependabot cannot find the Dockerfile
> ci: fix dependabot docker directory

- .github/workflows/publish.yml
The most common publishing failure we currently see is a 403 where the target repo indicates that the artifact in question is already present in the repo. We don't know how that happens, but ignoring the error in such a case is perfectly fine as the artifact is actually already present.
This commit adds the `--continue` Gradle flag to the publish call to ignore the 403s. To avoid trying to upload something that's completely broken but would pass the build due to `--continue`, the `build` call has been put into a separate workflow step and therefore Gradle
> fix(build): ignore 403s when publishing and just continue

- .github/dependabot.yml
Unfortunately dependabot currently does not support adding multiple directories, so the config is a bit repetitive.
> MODELIX-709 Use dependabot for npm and github-actions

- .github/dependabot.yml
The default has a different commit scope for dev dependencies, we want to have these unified.
> ci: configure dev deps prefix for dependabot

- api/model-server.yaml
- model-client/src/commonMain/kotlin/org/modelix/model/client2/IModelClientV2.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoriesManager.kt
- model-server/src/test/kotlin/org/modelix/model/server/ModelClientV2Test.kt
This MR proposes a /delete endpoint on the model server that could remove a repository. The endpoint is also available in the ModelClientV2. 
The feature was originally proposed by @nkoester in #237 (see its removal in [f97d2e8](https://github.com/modelix/modelix.core/pull/237/commits/f97d2e8b699089ec3d8e5d4dd50fa0e19e4b9225)).
> Introduce delete repository endpoint

- .github/dependabot.yml
The settings didn't configure the prefix for development dependencies and the settings were not applied to all NPM locations declared in the dependabot config.
> chore(deps): use the build(deps) prefix for all NPM dev updates

- .github/workflows/dry-run-release.yml
- .github/workflows/release.yaml
semantic-release now requires at least version 20. Missed that when merging the bump PR with all the red from the invalid commit messages.
> ci: bump node version in release workflow

- model-api-gen-gradle-test/ci.sh
- model-api-gen-gradle-test/kotlin-generation/src/test/kotlin/org/modelix/modelql/typed/TypedModelQLTest.kt
- model-api-gen-gradle-test/kotlin-generation/src/test/kotlin/org/modelix/modelql/typed/TypedModelQLTestWithLightModelServer.kt
- model-api-gen-gradle-test/kotlin-generation/src/test/kotlin/org/modelix/modelql/typed/TypedModelQLWithModelServerTest.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/INode.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- modelql-untyped/src/commonMain/kotlin/org/modelix/modelql/untyped/OfConceptStep.kt
These edge cases were not caught by the tests, because the client and server share the same `TypedLanguagesRegistry` as it is a a singleton.
In production the model-server would have no knowledge about the used languages, but it has them in our test.
If we wanted to test these cases automatically, we would probably have to test this with a real model-server, which would be quite expensive.
> MODELIX-714 ModelQl query on model-server fails with "issue getting concept"

- model-server/src/main/resources/org/modelix/model/server/store/database.properties
- model-server/src/main/resources/org/modelix/model/server/store/ignite.xml
Adds the database JVM property ignite.cache.size, which can be used to control the off heap Ignite cache size when using Postgres as a backend. The property defaults to the previous 100 Mb size.
Using the properties was a lot easier than providing a custom command line argument with the existing Spring XML config property configuration. Moreover, this is also more consistent as all database-related settings are controlled via properties.
I have skipped adding documentation because of the coordinated effort for documenting the model-server configuration planned in https://issues.modelix.org/issue/MODELIX-575 .
> feat(model-server): make the Ignite cache size configurable

- bulk-model-sync-gradle-test/build.gradle.kts
- bulk-model-sync-gradle-test/ci.sh
- bulk-model-sync-gradle-test/src/test/kotlin/org/modelix/model/sync/bulk/gradle/test/ChangeApplier.kt
- bulk-model-sync-gradle-test/src/test/kotlin/org/modelix/model/sync/bulk/gradle/test/PullTest.kt
- bulk-model-sync-gradle-test/src/test/kotlin/org/modelix/model/sync/bulk/gradle/test/PushTest.kt
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/ModelSyncGradlePlugin.kt
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/config/ModelSyncGradleSettings.kt
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/tasks/ImportIntoModelServer.kt
- docs/global/modules/core/pages/reference/component-bulk-model-sync-gradle.adoc
This PR adds the option for users to set arbitrary custom properties for the rootNode during the sync.
For example, users could store git metadata this way.
> MODELIX-718 Store Git metadata when syncing

- model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/CLVersion.kt
A test in the legacy-sync-plugin at https://github.com/modelix/modelix.mps-plugins/blob/d88add8f9b275e63d8eade850947fe892ad1ce7f/mps-legacy-sync-plugin/src/test/kotlin/ProjectCanBeCopiedAndSyncOnCloudTest.kt#L117 failed with the following exception:
```
java.lang.RuntimeException: Entry FR7gq*m60NNRgYGjc4qAtd-ND9uZvJryjBiXAQwzsNFQ not found
at org.modelix.model.lazy.WrittenEntry.getValue(WrittenEntry.kt:26)
at org.modelix.model.lazy.KVEntryReference.getValue(KVEntryReference.kt:43)
at org.modelix.model.lazy.CLVersion.getOperations(CLVersion.kt:156)
at org.modelix.model.lazy.CLVersionKt$computeDelta$oldAndNewEntries$1.invoke(CLVersion.kt:334)
at org.modelix.model.lazy.CLVersionKt$computeDelta$oldAndNewEntries$1.invoke(CLVersion.kt:302)
at …
```
> writing on ModelClientV2 failed when more than 10 changes were done

- .github/workflows/publish.yml
This allows pushing out PR states for testing under a snapshot release identifier.
This commit migrates the publish GitHub workflow from using custom bash scripts for publishing towards the commonly provided GitHub actions. That way, the decision when to publish which type of release is completely contained inside the publishing workflow. Without this change, the workflow and the scripts would often need simultaneous changes for reflecting desired publishing results.
> ci: allow publishing SNAPSHOT release via workflow_dispatch

- .github/workflows/publish.yml
Somehow this got set on my workflow_dispatch execution. I suspect the auto handling from the metadata action being the cause.
> ci: avoid setting the Docker latest tag for workflow_dispatch runs

- bulk-model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/bulk/ModelImporter.kt
- bulk-model-sync-lib/src/jvmTest/kotlin/org/modelix/model/sync/bulk/ModelImporterOrderPropertyTest.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/IChildLink.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/INode.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/SimpleChildLink.kt
Child links that are unordered are handled specially when importing using the bulk-model-sync. 
Such unordered children are not being reorder in when imported.
> Introduce ordered property for child links

- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoriesManager.kt
- model-server/src/test/kotlin/org/modelix/model/server/PullPerformanceTest.kt
- model-server/src/test/kotlin/org/modelix/model/server/StoreClientWithStatistics.kt
All objects of the model were loaded individually from the database. These many small requests resulted in a poor performance when running a bulk sync on an existing large model. Batch requests are now used to reduce the overhead.
> MODELIX-719 Performance of IModelClient2.pull

- model-api/src/commonMain/kotlin/org/modelix/model/api/INode.kt
- model-datastructure/build.gradle.kts
- model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/BulkQuery.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/CLTree.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/CLVersion.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/IBulkQuery.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/NonBulkQuery.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/NonCachingObjectStore.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/persistent/CPHamtInternal.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/persistent/CPHamtLeaf.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/persistent/CPHamtNode.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/persistent/CPHamtSingle.kt
- model-datastructure/src/jvmMain/kotlin/org/modelix/model/InMemoryModel.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/KeyValueLikeModelServer.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoriesManager.kt
- modelql-server/src/main/kotlin/org/modelix/modelql/server/ModelQLServer.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/IDefaultNodeAdapter.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSNode.kt
The versioning feature of our model data structure has the cost of a slower performance. To achieve a comparable performance to the light-model-server the whole model is now loaded into memory using a more efficient map implementation.
The model is update incrementally whenever the branch changes.
In the future we may be able to improve the performance by introducing indices and parallelizing the query execution (using IBulkQuery) and then might not need this in-memory model anymore.
> MODELIX-752 Improve model-server query performance by caching the model in memory

- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoriesManager.kt
- model-server/src/test/kotlin/org/modelix/model/server/ModelClientV2Test.kt
- model-server/src/test/kotlin/org/modelix/model/server/handlers/ModelReplicationServerTest.kt
In an optimization, only some of the referenced objects were emitted.
Making this this optimization correct emits more objects.
Also for not seending duplicate objects we have to keep a set of send object hashes while streaming objects.
> fix(model-server): respond with all objects if no base version was given

- model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoriesManager.kt
- model-server/src/test/kotlin/org/modelix/model/server/ModelClientV2Test.kt
Previously, sending objects failed quietly when the underlying channel was full. Now, the execution of the bulk query is blocked when the underlying channel is full.
> fix(model-server): RepositoriesManager.computeDelta should wait for channel to have capacity

- model-client/src/commonMain/kotlin/org/modelix/model/client2/IModelClientV2.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
This enhancement provides a more convenient and efficient way to use the pollHash method by eliminating the requirement to separately load and pass a version. Users can now directly specify the hash they want to use.
> feat(model-client): Add convenience method overload for pollHash

- bulk-model-sync-gradle-test/build.gradle.kts
- bulk-model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/bulk/ModelImporter.kt
- bulk-model-sync-mps/src/main/kotlin/org/modelix/mps/model/sync/bulk/MPSBulkSynchronizer.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/INode.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/SimpleProperty.kt
- model-api/src/commonMain/kotlin/org/modelix/model/data/ModelData.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/IDefaultNodeAdapter.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSDevKitDependencyAsNode.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSJavaModuleFacetAsNode.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSModelAsNode.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSModelImportAsNode.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSModuleAsNode.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSModuleDependencyAsNode.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSNode.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSProjectAsNode.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSProjectModuleAsNode.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSSingleLanguageDependencyAsNode.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/Util.kt
The renamings happen because the project used FilePerRootPersistence and MPS could not resolve the concept, as it was not loaded. As a fallback the filename would default to the id of the root node of a changed model.
However changes were made where none should have been. This PR fixes those cases.
> MODELIX-789 bulk-model-sync from model-server to MPS results in many renamed files without content changes

- bulk-model-sync-lib/build.gradle.kts
- bulk-model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/bulk/ModelImporter.kt
- kotlin-utils/build.gradle.kts
- kotlin-utils/src/commonMain/kotlin/org/modelix/kotlin/utils/DataStructures.kt
- kotlin-utils/src/jsMain/kotlin/org/modelix/kotlin/utils/DataStructures.js.kt
- kotlin-utils/src/jvmMain/kotlin/org/modelix/kotlin/utils/DataStructures.jvm.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/persistent/MapBasedStore.kt
This improves the memory footprint of the ModelClientV2. This in turn improves the memory footprint of bulk-model-sync.
> perf(model-datastructure): use a memory efficient map for MapBasedStore

- .github/dependabot.yml
The error log at
https://github.com/modelix/modelix.core/network/updates showed that it couldn't connect to
https://maven.pkg.github.com/modelix/modelix
Looks like dependabot also checks publishing repositories, which is unnecessary.
> ci: dependabot wasn't updating maven dependencies anymore

- model-server/src/main/kotlin/org/modelix/model/server/handlers/HistoryHandler.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/KeyValueLikeModelServer.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoriesManager.kt
- model-server/src/main/kotlin/org/modelix/model/server/store/IStoreClient.kt
- model-server/src/main/kotlin/org/modelix/model/server/templates/PageWithMenuBar.kt
- modelql-server/src/main/kotlin/org/modelix/modelql/server/ModelQLServer.kt
Execute them on Dispatchers.IO because they are mostly blocked by waiting for data from store. Long-running operations are `computeDelta` and `mergeChanges`.
> fix(model-server): do not execute long-running repository operation on request threads

- model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoryOverview.kt
- model-server/src/test/kotlin/org/modelix/model/server/handlers/RepositoryOverviewTest.kt
While the "Show History" link was already escaped properly to support slashes in both the repository id and branch name, it was not supported for the other links.
> fix(model-server): Escape slashes in path segments in repository overview

- model-server/src/main/kotlin/org/modelix/model/server/store/IgniteStoreClient.kt
- model-server/src/main/kotlin/org/modelix/model/server/store/InMemoryStoreClient.kt
- model-server/src/test/kotlin/org/modelix/model/server/IgniteStoreClientParallelTransactionsTest.kt
I tried out ThreadLocal and IgniteEvents.
ThreadLocals work.
With IgniteEvents we lose
* the ability to control if changes should be sent at all (`silent` parameter).
We could only control to ignore events for SHAs
Open: Check when we put things other than SHAs into store?
With IgniteEvents we gain:
* Simplifies code.
Open questions IgniteEvents:
* That hidden assumptions does it break?
* Are local events more or less much overhead than custom solution?
> Fix value changed notification

- .github/workflows/build.yaml
- model-server/build.gradle.kts
This PR adds reporting for test results via a PR comment as can be seen below.
Due to the current setup with additional test projects for the bulk sync and the generator, test results from these test projects are not included in the reporting. The reporting setup would be more complicated with multiple dependent jobs being needed. I don't think it's worth the effort, especially, given the ongoing work to change to a composite build for these tests.
FYI: the :zzz: is the number of skipped tests. Not an entirely intuitive emoji choice...
Fixes: MODELIX-792
> MODELIX-792: enable test result reporting in PR pipelines

- .github/workflows/build.yaml
- build.gradle.kts
- gradle/libs.versions.toml
- model-server/src/main/kotlin/org/modelix/model/server/handlers/HistoryHandler.kt
- model-server/src/main/kotlin/org/modelix/model/server/store/IgniteStoreClient.kt
Adds code coverage reporting via a PR comment. A hopefully uncontroversial change is included to demonstrate the per-file reporting in this PR.
JS reporting is unfortunately not too easy and excluded here.
The PR job artifacts include the full HTML coverage report.
Feel free to merge if the PR is ok as is.
Fixes: MODELIX-791
> MODELIX-791: enable coverage reporting in PR pipelines

- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- model-server/src/test/kotlin/org/modelix/model/server/ModelClientV2Test.kt
The optimization was previously only done to `ModelClientV2.poll`, `ModelClientV2.pullIfExists` and `ModelClientV2.pull`.
>  perf(model-client): consistently process version streams while receiving data

- gradle.properties
- model-api-gen-gradle-test/gradle.properties
This is something I stumbled upon [here](https://docs.gradle.org/current/userguide/performance.html#parallel_execution).
On my local machine this reduces the the time for a clean `./gradlew build` by about 40%.
> build: enable parallel gradle task execution

- bulk-model-sync-lib/build.gradle.kts
The test `can handle random changes` was often failing due to timeouts.
It fails because one test checks a hundred random cases.
`kotlin.test` does not support parametrized tests. Kotest would support it, but the `Annotation Spec` does not support Kotlin multiplatform.
Not wanting to decide on another testing style and rewrite the test, I just increased the timeout.
e.g. https://github.com/modelix/modelix.core/runs/23384531208
> test(bulk-model-sync): increase timeout of JS tests

- build.gradle.kts
- gradle/libs.versions.toml
It only adds debugging functionality that can be added to the build temporarily when needed.
> build: remove plugin com.dorongold.task-tree

- model-server/src/main/kotlin/org/modelix/model/server/Main.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/ContentExplorer.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/HistoryHandler.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/IRepositoriesManager.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/KeyValueLikeModelServer.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoriesManager.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoryOverview.kt
- model-server/src/test/kotlin/org/modelix/model/server/ModelServerTestUtil.kt
- model-server/src/test/kotlin/org/modelix/model/server/PullPerformanceTest.kt
- model-server/src/test/kotlin/org/modelix/model/server/ReplicatedRepositoryTest.kt
- model-server/src/test/kotlin/org/modelix/model/server/handlers/ModelReplicationServerTest.kt
Use `respondBytesWriter` because it has a non-blocking `writeStringUtf8` method. `respondTextWriter` has only blocking methods to write data.
Using a `Writer` is just an indirection without purpose.
> chore(model-server): use non-blocking method to send version delta

- bulk-model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/bulk/ModelImporter.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/INode.kt
- mps-model-adapters-plugin/src/test/kotlin/org/modelix/model/mpsadapters/ConceptResolutionTest.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSConcept.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSLanguageRepository.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSNode.kt
I took the courage to revert the commit, because it makes the new sync plugin fail. A workaround for the new new sync plugin is in [this PR](https://github.com/modelix/modelix.mps-plugins/pull/70).
Since I'm not familiar with the bulk-sync at all, I would leave the following task for someone with more experience.
> MODELIX-832: MPSLanguageRepository returns "unknown" Concept for unknown concepts

- bulk-model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/bulk/ModelImporter.kt
- bulk-model-sync-lib/src/commonTest/kotlin/org/modelix/model/sync/bulk/ModelImporterTest.kt
For unresolvable references we store the serialized expected reference, as we assume the node is not part of the model but the reference might still be useful for dynamic resolution on access. 
If the target node became part of the model later on, we did not update it because the originalIds still matched. Now we check, if it was previously unresolvable and update the reference to the INode accordingly.
> fix(bulk-model-sync): update previously unresolvable references if they can be resolved

- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- model-client/src/commonTest/kotlin/org/modelix/model/client2/ModelClientV2Test.kt
- model-client/src/jvmTest/kotlin/org/modelix/model/client2/ModelClientV2JvmTest.kt
- model-server-api/build.gradle.kts
- model-server-api/src/commonMain/kotlin/org/modelix/model/server/api/v2/VersionDeltaStreamV2.kt
- model-server-api/src/commonTest/kotlin/org/modelix/model/server/api/v2/VersionDeltaStreamV2Test.kt
- model-server-openapi/specifications/model-server.yaml
- model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
- model-server/src/test/kotlin/org/modelix/model/server/handlers/ModelReplicationServerTest.kt
Introduce a new version delta stream format that enables the client to properly detect incomplete delta version streams.
Old clients can still use the old format, but they might not detect incomplete streams.
> fix(model-client): detect incomplete version delta streams

- model-client/src/commonMain/kotlin/org/modelix/model/client2/IModelClientV2.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- model-server-openapi/specifications/model-server.yaml
- model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
- model-server/src/test/kotlin/org/modelix/model/server/ModelClientV2Test.kt
- model-server/src/test/kotlin/org/modelix/model/server/handlers/ModelReplicationServerTest.kt
Adds a new DELETE endpoint to the REST API for deleting a branch from a repository. Moreover, the ModelClient is extended with the matching `deleteBranch` method.
Garbage collection of data potentially not referenced anymore is not handled here and will be part of a later feature implementation.
> feat(model-server): implement deleting branches via REST API and ModelClient

- .idea/detekt.xml
- README.md
Adds the required configuration file for the IntelliJ plugin.
Fixes: MODELIX-793
> chore: configure the detekt IntelliJ plugin

- model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoriesManager.kt
- model-server/src/test/kotlin/org/modelix/model/server/handlers/ModelReplicationServerBackwardsCompatibilityTest.kt
Writing to a branch through V2 API already makes a branch visible through the V1 API. Making the branch visible after initial creation makes the backwards compatibility more consistent.
I found this issue while reviewing and testing #714
> fix(model-server): make initial branch created through V2 API visible in V1 API

- authorization/src/main/kotlin/org/modelix/authorization/KtorAuthUtils.kt
- model-server-openapi/specifications/model-server.yaml
- model-server/src/main/kotlin/org/modelix/model/server/Main.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/HttpException.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/KeyValueLikeModelServer.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
- model-server/src/test/kotlin/org/modelix/model/server/ModelServerTestUtil.kt
- model-server/src/test/kotlin/org/modelix/model/server/handlers/ModelReplicationServerTest.kt
This commit modifies the v2 REST API to always report errors as application/problem+json instances following RFC 9475. We do not declare this as a breaking change as we never guaranteed a certain error format.
The OpenAPI specification has been extended with a default error response for all routes to avoid having to repeat the definition many times.
The installation of the StatusPages extension had to be moved to the model-server Main file as this extension is now used to map instances of the new HttpException class to suitable responses.
HttpException has been introduced due to the lack of a standard HTTP exception hierarchy in ktor. Throwing exceptions instead of call.respondXXX usually makes route implementations shorter and easier to read.
> feat(model-server): report errors as application/problem+json

- .github/dependabot.yml
Avoids separate PRs for client and client-jetty.
#742 #741 will be grouped after this hopefully.
> ci: group com.google.oauth-client updates in dependabot

- model-client/src/commonMain/kotlin/org/modelix/model/client2/IModelClientV2.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- model-server/src/test/kotlin/org/modelix/model/server/ModelClientV2Test.kt
The `initRepository` endpoint of the model server has an optional useRoleIds parameter. Its default value is true on the server.
ModelClientV2 has an initRepository method that does not accept the useRoleIds parameter, so it sends the request without it. It may cause problem for the user, if they create a repository via the modelClient V2, and then load/read the model assuming it has role names instead of role IDs.
This PR adds the (optional) useRoleIds parameter to that method. The default value is true.
> feat(model-client): let the user set useRoleIds in the initRepository call

- kotlin-js-store/yarn.lock
- kotlin-utils/build.gradle.kts
- light-model-client/build.gradle.kts
- model-api-gen-runtime/build.gradle.kts
- model-server-api/build.gradle.kts
- modelql-client/build.gradle.kts
- modelql-core/build.gradle.kts
- modelql-html/build.gradle.kts
- modelql-typed/build.gradle.kts
- modelql-untyped/build.gradle.kts
The timeout was only configured for node.js, but not for the same JS test executed in the browser. The publishing workflow failed because of timeouts in these tests.
> MODELIX-904 Increase JS test timeout for modelql-core

- mps-model-adapters-plugin/src/test/kotlin/org/modelix/model/mpsadapters/ChangePropertyTest.kt
- mps-model-adapters-plugin/src/test/kotlin/org/modelix/model/mpsadapters/MpsAdaptersTestBase.kt
- mps-model-adapters-plugin/src/test/kotlin/org/modelix/model/mpsadapters/ReplaceNodeTest.kt
The result of `ThreadUtils.runInUIThreadAndWait` was previously ignored. Because of that tests that should have fail did not fail.
Also write needed to be executed inside a command.
Some tests need to be adapted because as they were, they failed.
> chore(mps-model-adapters): fix `writeActionOnEdt` in `MpsAdaptersTestBase`

- model-server-test/src/test/kotlin/IgnitePostgresTest.kt
- model-server/src/main/kotlin/org/modelix/model/server/store/ObjectInRepository.kt
- model-server/src/main/resources/org/modelix/model/server/store/ignite.xml
With different field order in Ignite configuration and key type `ObjectInRepository`, `IgniteCache.getAll` returned null values because keys were serialized differently. 
This only happened when `IgniteCache.getAll` was called with more than one key and the keys were not loaded into the cache. 
The serialization of a key return from a read-through operation was different from the serialization of a key created from an `ObjectInRepository` object.
> fix(model-server): fix `IgniteStoreClient.getAll` not returning values for existing entries

- model-server/src/test/kotlin/org/modelix/model/server/IgniteStoreClientParallelTransactionsTest.kt
`IgniteStoreClientParallelTransactionsTest` kept failing in CI with a timeout.
See https://github.com/modelix/modelix.core/actions/runs/9447363808/job/26021069325?pr=800#step:6:3371
> build(model-server): raise timeout for Ignite test

- model-api/src/commonMain/kotlin/org/modelix/model/api/INode.kt
There was a typo in https://github.com/modelix/modelix.core/commit/61ebd1df6cb819404aa12d8838265b004de61614, that flew under the radar and made it into production.
However, I just realized that due to this typo all of my Node IDs are wrong in the modelix sync plugin. Therefore this PR fixes the typo.
> fix(model-api): fix typo that breaks backwards compatibility

- docs/global/modules/core/pages/reference/component-model-api-gen.adoc
Stumbled on a typo in the docs that bothered me waaaaaay too much.
> docs: fix typo in model-api-gen

- docs/global/modules/core/pages/reference/component-model-api-gen-gradle.adoc
- model-api-gen-gradle/src/main/kotlin/org/modelix/metamodel/gradle/GenerateMetaModelSources.kt
- model-api-gen-gradle/src/main/kotlin/org/modelix/metamodel/gradle/MetaModelGradlePlugin.kt
- model-api-gen-gradle/src/main/kotlin/org/modelix/metamodel/gradle/MetaModelGradleSettings.kt
- model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/TypescriptMMGenerator.kt
- model-api-gen/src/test/kotlin/org/modelix/metamodel/generator/KotlinGeneratorTest.kt
This merge request adds a new optional property to the model api gen called `includeTypescriptBarrels `. When enabled it adds barrelling to the generated `index.ts` file as a convience feature. Example
```typescript
// index.ts (generated)
import { LanguageRegistry } from "@modelix/ts-model-api";
import { L_org_modelix_entities } from "./L_org_modelix_entities";
export function registerLanguages() {
LanguageRegistry.INSTANCE.register(L_org_modelix_entities.INSTANCE);
}
export * from "./L_org_modelix_entities";
// test.ts
import {N_Entity} from './index.ts'
// instead of 
import {N_Entity} from './L_org_modelix_entities.ts'
```
> feat(model-api-gen): allow generating typescript barrels

- model-api-gen-gradle-test/typescript-generation/build.gradle.kts
- model-api-gen-gradle-test/typescript-generation/jest.config.js
- model-api-gen-gradle-test/typescript-generation/package-lock.json
- model-api-gen-gradle-test/typescript-generation/package.json
- model-api-gen-gradle-test/typescript-generation/src/typeguards.test.ts
- model-api-gen-gradle-test/typescript-generation/tsconfig.json
- model-api-gen-gradle-test/vue-integration/package-lock.json
- model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/TypescriptMMGenerator.kt
- vue-model-api/package-lock.json
- Also added tests to `model-api-gen-gradle-test/typescript-generation` to verify the changes.
With the SingleChildAccessor you often find yourself writing code similar to this.
```typescript
const child = foo.bar.get();
if(child && isOfConcept_Child(child) {
// do your stuff
}
```
This change simplifies it so no additional null checking is needed anymore:
```typescript
const child = foo.bar.get();
if(isOfConcept_Child(child) {
// do your stuff
}
```
TODO description of the PR
> feat(model-api-gen): allow passing nullish values to concept type guards

- bulk-model-sync-lib/mps-test/build.gradle.kts
- bulk-model-sync-lib/mps-test/src/test/kotlin/org/modelix/model/sync/bulk/lib/test/ResolveInfoUpdateTest.kt
- bulk-model-sync-lib/mps-test/testdata/ResolveInfoUpdateTest/.mps/.gitignore
- bulk-model-sync-lib/mps-test/testdata/ResolveInfoUpdateTest/.mps/migration.xml
- bulk-model-sync-lib/mps-test/testdata/ResolveInfoUpdateTest/.mps/modules.xml
- bulk-model-sync-lib/mps-test/testdata/ResolveInfoUpdateTest/solutions/NewSolution/NewSolution.msd
- bulk-model-sync-lib/mps-test/testdata/ResolveInfoUpdateTest/solutions/NewSolution/models/NewSolution.a_model.mps
- bulk-model-sync-mps/src/main/kotlin/org/modelix/mps/model/sync/bulk/MPSBulkSynchronizer.kt
- gradle/libs.versions.toml
In projects, loading all libraries and plugins can take significant time. This workaround enables to sync projects better that do not want to load all libraries and plugins. With this workaround, the `name` or `resolveInfo` property of a target is used as the `resoleInfo` property on a reference even if the concept of the target could not be fully loaded.
> feat(bulk-model-sync): workaround removed and outdated resolveInfo after import into MPS

- model-api/src/commonMain/kotlin/org/modelix/model/api/IConcept.kt
- model-api/src/commonTest/kotlin/org/modelix/model/api/IConceptTests.kt
In MPS, we mostly have MPSConcepts, SimpleConcepts and GeneratedConcepts at runtime. 
If we use MPSConcept, then the IConcept.isSubConceptOf assumes that the superConcept is an MPSConcept. If not, then the method returns false. This makes it difficult to check if this and superConcept are the same superConcept if is a SimpleConcept. 
GeneratedConcept.isSubConceptOf checks the equality with the superConcept, which means if the superConcept is a different object that structurally may represent the same Concept then it returns false (e.g. a GeneratedConcept and a SimpleConcept with the same Concept UID and name would return false). 
In order to simplify all these cases we could just check the UID of the Concept and assume that if UID matches then the Concepts should also be the same. This …
> feat(model-api): check if is sub-concept but only based on the IConceptReference

- model-api-gen-gradle-test/typescript-generation/src/node.test.ts
- model-api-gen-gradle-test/typescript-generation/src/test-helpers.ts
- model-api-gen-gradle-test/typescript-generation/src/typeguards.test.ts
- model-api/build.gradle.kts
- model-api/src/jsMain/kotlin/org/modelix/model/api/NodeAdapterJS.kt
- model-api/src/jsTest/kotlin/org/modelix/model/api/NodeAdapterJSTest.kt
- ts-model-api/src/ChildrenAccessor.ts
- ts-model-api/src/INodeJS.ts
- ts-model-api/src/TypedNode.ts
- vue-model-api/src/internal/ReactiveINodeJS.test.ts
- vue-model-api/src/internal/ReactiveINodeJS.ts
This PR introduces convenience methods to the `ITypedNode` and `INodeJS` interfaces to easily remove any node from its parent in both the typed and untyped APIs.
Example usage: 
```typescript
const namedElement: INamedConcept = foo();
namedElement.remove();
// instead of
namedElement.unwrap().getParent()?.removeChild(namedElement.unwrap());
```
> feat(ts-model-api): add method for removing node

- model-api-gen-gradle-test/typescript-generation/package-lock.json
- model-api-gen-gradle-test/typescript-generation/src/ChildrenAccessor.test.ts
- model-api-gen-gradle-test/typescript-generation/src/test-helpers.ts
- model-api-gen-gradle-test/vue-integration/package-lock.json
- ts-model-api/src/ChildrenAccessor.ts
- vue-model-api/package-lock.json
Prior to this fix when using the `setNew` method of the `SingleChildAccessor` class, the created node had no concept and could not be given one. This PR introduces the possibility (while maintaining backwards compatibility) to provide a concept when invoking the method.
```typescipt
// before
const typedNode: BasePlaceholder = foo();
const childNode: IPlaceholderContent = typedNode.content.setNew(); // Actually UnknownTypedNode 
expect(isOfConcept_IPlaceholderContent(childNode)).toBeTruthy(); // <---- fails
// after
const typedNode: BasePlaceholder = foo();
const childNode: IPlaceholderContent = typedNode.content.setNew(C_IPlaceholderContent); 
expect(isOfConcept_IPlaceholderContent(childNode)).toBeTruthy(); // <---- succeeds
```
> fix(ts-model-api): new single childs can have correct concept

- .github/workflows/build.yaml
- .github/workflows/mps-compatibility.yaml
- .github/workflows/publish.yml
[gradle/gradle-build-action has been replaced by gradle/actions/setup-gradle](https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlegradle-build-action-has-been-replaced-by-gradleactionssetup-gradle)
> ci: replace deprecated gradle action

- bulk-model-sync-mps/build.gradle.kts
- gradle/libs.versions.toml
- mps-model-adapters/build.gradle.kts
We had the ~19-year-old Trove and the ~12-year-old Trove4j on the CP. To avoid confusion and to keep the dependencies up to date, I replaced the former with the latter, because that is the continuation of that library.
> build(deps): replace deprecated trove with trove4j

- .github/workflows/dependabot-auto-merge.yaml
This should set minor and patch updates to auto-merge and approve them automatically.
As long as the pipelines are green it should then be merged automatically.
> MODELIX-938 Configure dependabot to merge patch versions automatically

- .github/workflows/dependabot-auto-merge.yaml
> ci: add missing contents permission to dependabot-auto-merge workflow

- model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/IndirectObjectStore.kt
- model-server/src/test/kotlin/org/modelix/model/server/handlers/KeyValueLikeModelServerTest.kt
Fix executing bulk queries in `RestWebModelClient`.
> fix(model-client): fix executing bulk queries in RestWebModelClient

- ts-model-api/.eslintrc.json
- ts-model-api/package-lock.json
- ts-model-api/package.json
- ts-model-api/src/LanguageRegistry.ts
- ts-model-api/tsconfig.json
Upgrade TypeScript to 5.4.2
Replace the deprecated compiler option `importsNotUsedAsValues` with linting rules.
The new suggested compiler option `verbatimModuleSyntax` does not allow writing ESM syntax in files that will emit as CommonJS.
That is what we do.
To not rewrite the code but disable the things disabled by `importsNotUsedAsValues` the new linting rules were added.
An in-depth explanation can be found at https://johnnyreilly.com/typescript-5-importsnotusedasvalues-error-eslint-consistent-type-imports
> build(deps): bump typescript from 4.9.5 to 5.4.2 in /ts-model-api

- model-api-gen-gradle-test/typescript-generation/build.gradle.kts
- model-api-gen-gradle-test/vue-integration/build.gradle.kts
- modelql-core/build.gradle.kts
- ts-model-api/build.gradle.kts
- vue-model-api/build.gradle.kts
Replace `create` with `register` and `creating` with `registering`.
> build: avoid task configuration in Grade builds

- vue-model-api/package-lock.json
- vue-model-api/src/index.ts
- vue-model-api/src/useReplicatedModel.test.ts
- vue-model-api/src/useReplicatedModel.ts
Expose replicated model in Vue.js API.
The replicated model can be used to subscribe to changes on the branch or get information about the current version.
> feat(vue-model-api): expose replicated model

- .github/workflows/docs.yaml
Without this option the CNAME file is deleted every deployment, leading to 404s.
TODO description of the PR
> ci: add cname to api ref workflow

- model-api-gen-gradle-test/vue-integration/build.gradle.kts
Documenation of build files for future developers and myself 😆
> chore(model-api-gen): add comment about "updateDependencies" task from NPM packages

- gradle/libs.versions.toml
- model-server-openapi/specifications/model-server-v2.yaml
- model-server/build.gradle.kts
- model-server/src/main/kotlin/org/modelix/model/server/Main.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
- model-server/src/main/resources/openapi/templates/Paths.kt.mustache
- model-server/src/main/resources/openapi/templates/api.mustache
- model-server/src/test/kotlin/org/modelix/model/server/ModelServerTestUtil.kt
- model-server/src/test/kotlin/org/modelix/model/server/handlers/ModelReplicationServerTest.kt
This PR adds a new media type for requesting branch metadata as the first test case to prepare for media-type versioning. To achieve this versioning the scheme, the PR modifies the openapi-generator templates so that one can optionally declare separate handler methods per media type(s) to generate in the API interface.
This PR also adds kotest-assertions and therefore closes MODELIX-795
> MODELIX-949: media type versioning + branch meta data access

- model-server-openapi/specifications/model-server-operative.yaml
Fixes the missing response specification for a healthy /health reply.
> fix(model-server): provide a valid operative spec

- .github/workflows/linting.yml
This PR enables linting the OpenAPI specifications for breaking changes. For this purpose, the most recent version of the specs is compared to the specs present at the time the PR branched off. In case of findings, those are presented as inline annotations in the diff:
Currently, most detected findings have no line association and are therefore attached to the top of the openapi spec.
Breaking changes are detected after internally fusing all specs. That way, we would be free to move routes from one file to the other without triggering a breaking change (`composed` mode of oasdiff).
The added linter is not mandatory and does not fail the build, assuming that sometimes performing breaking changes is fine if no known uses exist.
> MODELIX-950: lint for OpenAPI breaking changes

- model-api-gen-gradle-test/kotlin-generation/src/test/kotlin/org/modelix/metamodel/generator/GeneratedApiTest.kt
- model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/internal/ConceptObjectGenerator.kt
- model-api-gen/src/main/kotlin/org/modelix/metamodel/generator/internal/ConceptWrapperInterfaceGenerator.kt
- modelql-client/src/jvmTest/kotlin/org/modelix/modelql/client/HtmlBuilderTest.kt
Generated concepts did not implement `getConceptProperty(name: String)`.
The generated code now roughly looks like this:
```kotlin
public object _C_UntypedImpl_MyConcept {
override fun getConceptProperty(name: String): String? = when (name) {
"alias" -> C_MyConcept.alias
else -> null
}
}
public interface C_MyConcept {
companion object : C_MyConcept {
override val alias: String = "my concept alias"
}
}
```
> MODELIX-969 conceptAlias does not seem to work

- authorization/src/main/kotlin/org/modelix/authorization/AuthorizationConfig.kt
#678 did not let the `AuthorizationConfig.jwkKeyId` to be set from a system envvar. This PR fixes this bug.
`jwkKeyId` is used when we load the JWK from a URI and [we want to select from the bunch of JWKs the one to use](https://github.com/modelix/modelix.core/blob/df0e3649dd3d4c38708ac3632ab8a69bfc7ffcd4/authorization/src/main/kotlin/org/modelix/authorization/AuthorizationConfig.kt#L137).
> fix(model-server): set jwkKeyId from system envvar

- gradle/libs.versions.toml
- model-api/build.gradle.kts
- model-api/src/commonMain/kotlin/org/modelix/model/api/BuiltinLanguages.kt
- model-api/src/commonMain/kotlin/org/modelix/model/api/IConcept.kt
- model-api/src/commonTest/kotlin/org/modelix/model/api/BuiltinLanguagesTest.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSConcept.kt
Add UID for `INamedConcept`.
The UID was missing for some reason.
This made me run into errors testing when testing the sync plugin.
> fix(model-api): add UID for INamedConcept

- model-api/build.gradle.kts
- model-api/src/commonMain/kotlin/org/modelix/model/data/ModelData.kt
- model-api/src/commonTest/kotlin/org/modelix/model/data/ModelDataTest.kt
Do not require registered concept for serialization to `NodeData`.
> fix(model-api): do not require registered concept for serialization to NodeData

- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/ModelSyncGradlePlugin.kt
- bulk-model-sync-gradle/src/main/kotlin/org/modelix/model/sync/bulk/gradle/config/ModelSyncGradleSettings.kt
- docs/global/modules/core/pages/reference/component-bulk-model-sync-gradle.adoc
In simple cases, `MPSBulkSynchronizer` does not rely on concepts (and in turn of languages and plugins) of the synced nodes to be loaded. 
Plugins might become necessary when they provide custom persistence and in other, yet unknown cases.
Depends on https://github.com/modelix/modelix.mps-build-tools/pull/52. 
After it is merged and published `libs.versions.toml` needs to be updated. But the API in bulk-sync-plugin can be reviewed anyway.
I did not add tests.
The test would be complicated, long-running (starts MPS) and only test rather simple logic.
When someone deems test necessary I would add tests, that run one of the sync tasks and assert through the logs, that the specified plugins are loaded.
If someone has a better idea/different opinion on the tests here, please let me know.
> feat(bulk-model-sync): add a configuration option to load plugins

- light-model-client/build.gradle.kts
- light-model-client/src/jvmTest/kotlin/org/modelix/client/light/FakeLightModelServer.kt
- light-model-client/src/jvmTest/kotlin/org/modelix/client/light/LightModelClientTest.kt
The implementation `org.modelix.model.server.handlers.LightModelServer` was only used as a fake to test the light-model-client.
Renaming and moving it into the test code of the light-model-client helps to understand that.
The light-model-server implementation running in MPS is `org.modelix.model.server.light.LightModelServer`.
The next step would be to remove `FakeLightModelServer` and use `org.modelix.model.server.light.LightModelServer` to test the light-model-client.
See MODELIX-994
> chore(model-server): remove implementation of `LightModelServer` from model-server code

- .pre-commit-config.yaml
This fixes local commitlint failing when used locally for some users.
> build(deps): bump commitlint-pre-commit-hook from v9.4.0 to v9.16.0

- renovate.json5
"build" is the prefix we are using with Dependabot.
> ci: configure commit type "build" for Renovate

- model-server/src/main/kotlin/org/modelix/model/server/Main.kt
needed for in-browser clients
So far, I receive a 403 for an OPTIONS request that includes `access-control-request-headers:Authorization`. This PR intends to fix that (I didn't test this locally yet).
For example:
```bash
http OPTIONS :28101/v2/generate-client-id access-control-request-method:POST access-control-request-headers: Origin:http://localhost:5173
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: OPTIONS, PUT
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 86400
Connection: keep-alive
Content-Length: 0
```
```bash
http OPTIONS :28101/v2/generate-client-id access-control-request-method:POST access-control-request-headers:Authorization Origin:http://localhost:5173
HTTP/1.1 403 Forbidden
Connection: keep-alive
Content-Length: 0
``` …
> allow Authorization header to be sent from foreign origins

- mps-model-adapters-plugin/src/test/kotlin/org/modelix/model/mpsadapters/MPSModuleAsNodeTest.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSModuleAsNode.kt
Fixes a wrong lookup in `findSingleLanguageDependency`.
> fix(mps-model-adapters): resolve language dependency correctly in `MPSModuleAsNode`

- bulk-model-sync-lib/src/commonMain/kotlin/org/modelix/model/sync/bulk/ModelSynchronizer.kt
- bulk-model-sync-lib/src/commonTest/kotlin/org/modelix/model/sync/bulk/ModelSynchronizerTest.kt
- bulk-model-sync-lib/src/jvmTest/kotlin/org/modelix/model/sync/bulk/ModelSynchronizerWithInvalidationTreeTest.kt
The test cases can not be easily generalized.
It is fine to test this only for the ModelSynchronizer because bulk-model-sync-gradle-test already covers these cases for the ModelImporter.
> MODELIX-1008 Sync with subtree skipping fails syncing new node to MPS

- gradle/libs.versions.toml
- model-api-gen/build.gradle.kts
https://github.com/modelix/modelix.core/commit/50a7dec90b963a41320cd6dbd702fd69b6364e14 removed the dependency from some of the `build.gradle.kts` files.
I forgot to remove it from the `libs.versions.toml` and missed an instance in `model-api-gen.`
>  build(deps): remove dependency kotlinx-collections-immutable

- model-datastructure/src/commonMain/kotlin/org/modelix/model/LinearHistory.kt
- model-datastructure/src/commonTest/kotlin/LinearHistoryTest.kt
Previously, calculating the linear history between the same version resulted in linear history that contained more than only that one version.
This in turn resulted in needles computations and deltas that were too big.
Fixes: MODELIX-1025
> fix(model-datastructure): correctly calculate linear history between the same version

- kotlin-js-store/yarn.lock
- model-client/build.gradle.kts
Updated the  [ws npm dependency](https://www.npmjs.com/package/ws) in the `model-client` module to mitigate  [CVE-2024-37890](https://nvd.nist.gov/vuln/detail/CVE-2024-37890) which was fixed with version [8.17.1](https://github.com/websockets/ws/releases/tag/8.17.1)
> build(deps): fix version of ws to mitigate CVE-2024-37890

- model-server/src/main/kotlin/org/modelix/model/server/ModelServerPermissionSchema.kt
Legacy permissions (used by model client V1) were not included in the admin permission.
> Include legacy-* permissions in admin permission

- authorization/src/main/kotlin/org/modelix/authorization/AuthorizationConfig.kt
- authorization/src/main/kotlin/org/modelix/authorization/AuthorizationPlugin.kt
- docs/global/modules/core/pages/reference/component-model-server.adoc
- gradle/libs.versions.toml
- model-server/build.gradle.kts
- model-server/src/test/kotlin/org/modelix/model/server/AuthorizationTest.kt
- model-server/src/test/resources/logback-test.xml
If no static key ID is configured, then the key ID specified in the JWT is used to verify the token. The key is looked up at the JWK URL with the key ID from the token.
This is a fix because it restores functionality that accidentally broke in version 8.14.0.
> fix(model-server): make specifying a key ID optional

- model-client/integration-tests/build.gradle.kts
Calling `dockerCompose.isRequiredBy(tasks.named("jsNodeTest"))` with `org.gradle.parallel=true` caused issues when running the Gradle task `prepareKotlinIdeaImport`. That task was run by Intellij when trying to import the Gradle project. The import failed when the task failed.
> build(model-client): change Gradle configuration to avoid failing import into Intellij

- vue-model-api/package.json
- vue-model-api/src/internal/Cache.test.ts
- vue-model-api/src/internal/ReactiveINodeJS.test.ts
- vue-model-api/src/internal/ReactiveINodeJS.ts
- vue-model-api/src/internal/handleChange.ts
- vue-model-api/src/internal/runGarbageCollection.test.ts
- vue-model-api/src/internal/runGarbageCollection.ts
- vue-model-api/src/internal/useLastPromiseEffect.ts
- vue-model-api/tsconfig.json
Garbage collection broke the `vue-model-api` as shown the added test.
Correctly using Vue refs fixes it.
> fix(vue-model-api): do not evict ReactiveINodeJS from cache when objects manged by it are still used

- model-server-openapi/specifications/model-server-v2.yaml
- modelql-client/src/jvmTest/kotlin/org/modelix/modelql/client/ModelQLClientTest.kt
- modelql-core/src/commonMain/kotlin/org/modelix/modelql/core/Query.kt
- modelql-server/src/main/kotlin/org/modelix/modelql/server/ModelQLServer.kt
- streams/src/commonMain/kotlin/org/modelix/streams/StreamExtensions.kt
When a modelql query fails due to a mismatch between what's expected by the query and the underlying data, always returns the same status code.
I have chosen 422 here. 5xx status codes are reserved for actual application failures instead of business logic errors. 404 would be too specific. 422 looks like it covers all kinds of errors related to being unable to "process" an otherwise valid query successfully.
> feat(model-server)!: use a consistent status code for query failures

- authorization/src/main/kotlin/org/modelix/authorization/ModelixJWTUtil.kt
- authorization/src/test/kotlin/org/modelix/authorization/RSATest.kt
If the Kubernetes secret containing the RSA key changed, the container usually isn't restarted, so we have to make sure we don't use an outdated key.
> fix(authorization): reload keys when the file changes

- .github/workflows/build.yaml
The action started failing because `ubuntu-latest` change from `ubuntu-22.04` to `ubuntu-24.04` and does not have packages for ICU installed by default.
Because we do not need globalization support, we can just disable it.
Fixes https://github.com/modelix/modelix.core/actions/runs/12399750050/job/34617726915
> ci: disable globalization support when running @microsoft/sarif-multitool

- .github/dependabot.yml
- .github/workflows/build.yaml
- .github/workflows/dependabot-auto-merge.yaml
- .github/workflows/docs.yaml
- .github/workflows/dry-run-release.yml
- .github/workflows/linting.yml
- .github/workflows/mps-compatibility.yaml
- .github/workflows/publish.yml
- .github/workflows/release.yaml
- renovate.json5
Compared to Dependabot Renovate:
* updates the versions of GitHub runners[^1]
* pins the version of actions[^2]
[^1]: https://github.com/odzhychko/modelix.core/pull/8
[^2]: https://github.com/odzhychko/modelix.core/pull/7
> ci: Use Renovate to update GitHub actions

- modelql-untyped/build.gradle.kts
- modelql-untyped/src/commonMain/kotlin/org/modelix/modelql/untyped/UntypedModelQL.kt
- modelql-untyped/src/commonTest/kotlin/org/modelix/modelql/untyped/UntypedModelQLTest.kt
Fixes https://issues.modelix.org/issue/MODELIX-997
> fix(modelql): set `INodeResolutionScope` when running query on `INode`

- mps-model-adapters-plugin/src/test/kotlin/org/modelix/model/mpsadapters/ReplaceNodeTest.kt
- mps-model-adapters-plugin/testdata/SimpleProject/solutions/Solution1/models/Solution1.model1.mps
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSNode.kt
* correctly parse concept UID
* check preconditions before making changes
* remove child from parent before moving to new parent
* correctly call `SNode.insertChildBefore`
> fix(mps-model-adapters): fix MPSNode.replaceNode

- gradle/libs.versions.toml
- modelql-server/build.gradle.kts
Some decencies were unused. Others are already provided transitively by other dependencies.
> build(modelql): remove unneeded dependencies in modelql-server

- bulk-model-sync-lib/src/commonTest/kotlin/org/modelix/model/sync/bulk/AbstractModelSyncTest.kt
On CI it still runs into the 60s timeout sometimes.
> test(bulk-model-sync-lib): fix flaky test `can handle random changes`

- model-client/src/commonMain/kotlin/org/modelix/model/client2/ReplicatedModel.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/IVersion.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/CLVersion.kt
- model-server/src/test/kotlin/org/modelix/model/server/LazyLoadingTest.kt
- model-server/src/test/kotlin/org/modelix/model/server/ModelServerTestUtil.kt
- model-server/src/test/kotlin/org/modelix/model/server/ReplicatedRepositoryTest.kt
The JS client doesn't support blocking requests. If during real-time collaboration the client tries to merge the history with the remote version, it may need more of the history than what was previously downloaded.
The algorithm in ReplicatedModel was changed to just let the server do the merge and avoid downloading additional history to the client.
> fix(model-client): ReplicatedModel was throwing LazyLoadingDisabledException on JS

- model-client/build.gradle.kts
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- model-client/src/commonMain/kotlin/org/modelix/model/oauth/ModelixAuthClient.kt
- model-client/src/commonMain/kotlin/org/modelix/model/oauth/OAuthConfig.kt
- model-client/src/jsMain/kotlin/org/modelix/model/oauth/ModelixAuthClient.kt
- model-client/src/jvmMain/kotlin/org/modelix/model/client/RestWebModelClient.kt
- model-client/src/jvmMain/kotlin/org/modelix/model/oauth/ModelixAuthClient.kt
- model-client/src/jvmTest/kotlin/org/modelix/model/client2/OAuthTest.kt
- model-client/src/jvmTest/kotlin/org/modelix/model/client2/TokenEndpointTest.kt
- mps-sync-plugin3/src/main/kotlin/org/modelix/mps/sync3/AppLevelModelSyncService.kt
- mps-sync-plugin3/src/main/kotlin/org/modelix/mps/sync3/IModelSyncService.kt
- mps-sync-plugin3/src/main/kotlin/org/modelix/mps/sync3/ModelSyncService.kt
A token URL can now contain a placeholder `{repositoryId}` which is replaced with the repository ID the sync plugin tries to access.
> feat(mps-sync-plugin): repositoryId can be passed to the token endpoint

- model-api/src/commonMain/kotlin/org/modelix/model/api/SimpleConcept.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/lazy/CLVersion.kt
- mps-sync-plugin3/src/main/kotlin/org/modelix/mps/sync3/BindingWorker.kt
- mps-sync-plugin3/src/test/kotlin/org/modelix/mps/sync3/ProjectSyncTest.kt
If a repository was already initialized, but didn't contain any data yet, the plugin still ignored the local project and tried to check out the remote version, which failed.
> fix(mps-sync-plugin): initial sync was trying to checkout an empty repository

- mps-sync-plugin3/src/main/kotlin/org/modelix/mps/sync3/AppLevelModelSyncService.kt
- mps-sync-plugin3/src/main/kotlin/org/modelix/mps/sync3/IModelSyncService.kt
- mps-sync-plugin3/src/main/kotlin/org/modelix/mps/sync3/ModelSyncService.kt
The `.mps/modelix.xml` file can now contain two new entries `oauthClientId` and `oauthClientSecret`.
> feat(mps-sync-plugin): OAuth client ID and secret are configurable

- model-datastructure/build.gradle.kts
libraries should not depend on slf4j-bindings to avoid https://www.slf4j.org/codes.html#multiple_bindings
> fix(model-datastructure): no longer depend on the slf4j-binding logback-classic

- model-api/src/commonMain/kotlin/org/modelix/model/api/PNodeReference.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/datastructures/model/GenericModelTree.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/VersionMerger.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/mutable/AutoTransactionsModelTree.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/mutable/IGenericMutableModelTree.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/mutable/INodeIdGenerator.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/mutable/ThreadSafeMutableModelTree.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/mutable/VersionedModelTree.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/operations/AddNewChildOp.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/operations/CapturedInsertPosition.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/operations/LegacyBranchAsMutableModelTree.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/operations/MoveNodeOp.kt
- model-datastructure/src/commonTest/kotlin/DuplicateImportConflictTest.kt
- model-datastructure/src/commonTest/kotlin/RandomTreeChangeGenerator.kt
- mps-sync-plugin3/src/test/kotlin/org/modelix/mps/sync3/ProjectSyncTest.kt
After preserving the identity of nodes during an import by the mps-sync-plugin it can happen that two imports both create a AddNewChildOp with the same child ID. During a merge this is a new type of conflict that wasn't handled yet.
> fix(model-datastructure): handle conflict between operations that add the same node

- model-api/src/commonMain/kotlin/org/modelix/model/data/ModelData.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/IModelClientV2.kt
- model-client/src/commonMain/kotlin/org/modelix/model/client2/ModelClientV2.kt
- model-server-openapi/specifications/model-server-v2.yaml
- model-server/src/main/kotlin/org/modelix/model/server/handlers/IRepositoriesManager.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/ModelReplicationServer.kt
- model-server/src/main/kotlin/org/modelix/model/server/handlers/RepositoriesManager.kt
- model-server/src/test/kotlin/org/modelix/model/server/RepositoryMigrationTest.kt
- mps-sync-plugin3/src/test/kotlin/org/modelix/mps/sync3/ProjectSyncTest.kt
The mps-sync-plugin only supports repositories that use string node IDs. Existing repositories that still use int64 IDs can now be migrated.
> feat(model-server): repository can be migrated from int64 to string IDs

- model-client/src/jvmMain/kotlin/org/modelix/model/oauth/ModelixAuthClient.kt
- model-client/src/jvmTest/kotlin/org/modelix/model/client2/RefreshTokenTest.kt
Previously, the model client just continued trying to request a new access token using the invalid refresh token.
Now, it discards the invalid refresh token and initiates a new PKCE flow.
> fix(model-client): discard invalid refresh tokens

- model-client/src/jvmTest/kotlin/org/modelix/model/client2/RefreshTokenTest.kt
- model-datastructure/src/commonMain/kotlin/org/modelix/model/mutable/SingleThreadMutableModelTree.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSModelAsNode.kt
- mps-model-adapters/src/main/kotlin/org/modelix/model/mpsadapters/MPSModuleAsNode.kt
- mps-sync-plugin3/src/test/kotlin/org/modelix/mps/sync3/ProjectSyncTest.kt
- mps-sync-plugin3/testdata/model-dependencies/.mps/.gitignore
- mps-sync-plugin3/testdata/model-dependencies/.mps/migration.xml
- mps-sync-plugin3/testdata/model-dependencies/.mps/modules.xml
- mps-sync-plugin3/testdata/model-dependencies/.mps/vcs.xml
- mps-sync-plugin3/testdata/model-dependencies/devkits/NewDevkit/NewDevkit.devkit
- mps-sync-plugin3/testdata/model-dependencies/languages/NewLanguage/NewLanguage.mpl
- mps-sync-plugin3/testdata/model-dependencies/languages/NewLanguage/generator/templates/NewLanguage.generator.templates@generator.mps
- mps-sync-plugin3/testdata/model-dependencies/languages/NewLanguage/generator1/templates/NewLanguage.generator01.templates@generator.mps
- mps-sync-plugin3/testdata/model-dependencies/languages/NewLanguage/models/NewLanguage.behavior.mps
- mps-sync-plugin3/testdata/model-dependencies/languages/NewLanguage/models/NewLanguage.constraints.mps
- mps-sync-plugin3/testdata/model-dependencies/languages/NewLanguage/models/NewLanguage.editor.mps
- mps-sync-plugin3/testdata/model-dependencies/languages/NewLanguage/models/NewLanguage.structure.mps
- mps-sync-plugin3/testdata/model-dependencies/languages/NewLanguage/models/NewLanguage.typesystem.mps
- mps-sync-plugin3/testdata/model-dependencies/solutions/NewRuntimeSolution/NewRuntimeSolution.msd
- mps-sync-plugin3/testdata/model-dependencies/solutions/NewRuntimeSolution/models/NewRuntimeSolution.plugin.mps
- mps-sync-plugin3/testdata/model-dependencies/solutions/NewSolution/NewSolution.msd
- mps-sync-plugin3/testdata/model-dependencies/solutions/NewSolution/models/NewSolution.a_model.mps
- mps-sync-plugin3/testdata/model-dependencies/solutions/NewSolution/models/NewSolution.b_model.mps
- mps-sync-plugin3/testdata/model-dependencies/solutions/NewSolution/models/NewSolution.toBeDeletedModel.mps
- mps-sync-plugin3/testdata/model-dependencies/solutions/ToBeDeleted/ToBeDeleted.msd
Model imports were not synchronized if the target modes is not part of the synchronization (doesn't exist on the server).
The synchronizer tried to resolve the model node and read the model ID, but since we use the original IDs from MPS this information can also be derived from that ID.
> fix(mps-sync-plugin): model imports of target models not part of the synchronization
